export {
  AotFrameworkLinkPackageError,
  readAotFrameworkLinkPackage,
  type AotFrameworkLinkPackage,
  type AotFrameworkLinkPackageFile,
  type AotFrameworkLinkPackageModule,
  type AotFrameworkLinkPackageRequest,
} from './framework-link-package.js';
export {
  AotCompilerPatchModuleEmitter,
  type AotCompilerPatchModuleArtifact,
  type AotCompilerPatchModuleEmissionRequest,
} from './compiler-patch-module-emitter.js';
export {
  AOT_COMPILER_PATCH_RUNTIME_MODULE_ID,
  AOT_COMPILER_PATCH_RUNTIME_MODULE_SOURCE,
} from './compiler-patch-runtime-module.js';
export {
  AOT_FRAMEWORK_LINK_MAP_POSTURE,
  AOT_FRAMEWORK_LINK_PROTOCOL,
  AOT_RC2_FRAMEWORK_LINK_EXPECTATIONS,
  AOT_RC2_FRAMEWORK_LINK_GRAPH_FINGERPRINT,
  AOT_RC2_FRAMEWORK_LINK_OPERATION,
  AOT_RC2_FRAMEWORK_LINK_RECIPE_FINGERPRINT,
  AOT_RC2_LINK_MODULES_GRAPH_FINGERPRINT,
  AOT_RC2_LINK_MODULES_EXPECTATIONS,
  AotFrameworkLinkEmitter,
  AotFrameworkLinkError,
  type AotFrameworkLinkErrorCode,
  type AotFrameworkLinkPolicy,
  type AotFrameworkLinksC0FallbackReason,
  type AotFrameworkLinksC0FallbackReasonKind,
  type AotFrameworkLinksOptions,
  type AotFrameworkLinkMapPosture,
  type AotFrameworkLinkModuleInput,
  type AotFrameworkLinkModuleRole,
  type AotFrameworkLinkPackageInput,
  type AotFrameworkLinkPackageModuleArtifact,
  type AotLinkedFrameworkPackageArtifact,
  type AotFrameworkLinkSessionAdmission,
  type AotLinkedFrameworkModuleArtifact,
  type AotPrepareFrameworkLinkModule,
  type AotPrepareFrameworkLinksRequest,
  type AotPrepareFrameworkLinksResult,
  type AotPreparedFrameworkLinksApplied,
  type AotPreparedFrameworkLinksC0Fallback,
} from './framework-link.js';
export {
  AotArtifactError,
  AotTemplateModuleEmitter,
  type AotArtifactErrorCode,
  type AotRawSourceMap,
  type AotTemplateModuleArtifact,
  type AotTemplateModuleEmissionRequest,
} from './template-module-emitter.js';
export {
  AOT_COMPILER_PATCH_PAYLOAD_MODULE_PREFIX,
  SemanticAotArtifactProvider,
  SemanticAotBuildSession,
  frameworkLinkSessionAdmission,
  type SemanticAotArtifactEvidence,
  type SemanticAotBuildRequest,
  type SemanticAotRuntimeConfigurationEvidence,
  type SemanticAotRuntimeConfigurationMode,
  type SemanticAotRuntimeConfigurationOccurrenceEvidence,
  type SemanticAotSourceTransformArtifact,
  type SemanticAotSourceTransformRequest,
  type SemanticAotTemplateArtifact,
  type SemanticAotTemplatePayloadReference,
  type SemanticAotTemplateRequest,
  type SemanticAotTemplateResourceIdentity,
  type SemanticAotVirtualModuleArtifact,
  type SemanticAotVirtualModuleRequest,
} from './semantic-artifact-provider.js';
export {
  AOT_RUNTIME_MODULE_SPECIFIER,
  AotSourceTransformEmitter,
  AotSourceTransformError,
  type AotSourceTransformArtifact,
  type AotSourceTransformBrowserFacadePlan,
  type AotSourceTransformConfigurationPlan,
  type AotSourceTransformErrorCode,
  type AotSourceTransformRequest,
  type AotSourceTransformResourcePlan,
  type AotSourceTransformSlice,
  type AotTransformedBrowserFacade,
  type AotTransformedConfiguration,
  type AotTransformedResource,
} from './source-transform.js';
export {
  AOT_CONSERVATIVE_RUNTIME_REGISTRATION_ORDER,
  AOT_RUNTIME_CONFIGURATION_MODULE_PREFIX,
  AOT_RUNTIME_CONFIGURATION_PROTOCOL,
  AOT_RUNTIME_SPREAD_PLAN,
  AOT_RUNTIME_SPREAD_PLAN_PROTOCOL,
  AotExpressionParser,
  AotRuntimeConfiguration,
  AotRuntimeConfigurationModuleEmitter,
  AotRuntimeConfigurationPlan,
  AotTemplateCompiler,
  type AotRuntimeCoercionOptions,
  type AotRuntimeConfigurationModuleArtifact,
  type AotRuntimeExpressionEntry,
  type AotRuntimeExpressionType,
  type AotRuntimeRegistrationPlan,
  type AotRuntimeRegistrationReference,
  type AotRuntimeRegistrationKind,
  type AotRuntimeRegistrationSelection,
  type AotRuntimeSpreadPlan,
  type AotRuntimeSpreadPlanCase,
  type AotRuntimeSpreadTargetDefinitionMatch,
} from './runtime-configuration.js';
