import { SourcePatternModule, SourcePatternModuleKey, SourcePatternModuleKind } from './source-plan.js';

/** Shared source-pattern modules used to describe reusable app-building architecture without copying scenario nouns. */
export const SourcePatternModules = {
  AppShell: new SourcePatternModule(
    SourcePatternModuleKey.AureliaAppShell,
    SourcePatternModuleKind.AppShell,
    'Aurelia app shell',
    'Public Aurelia entrypoint plus root component/template ownership.',
  ),
  ConventionResource: new SourcePatternModule(
    SourcePatternModuleKey.ConventionResourceAdmission,
    SourcePatternModuleKind.ResourceConvention,
    'Convention resource admission',
    'Class/file/template naming is intentionally compatible with Aurelia convention resource discovery.',
  ),
  ExplicitResourceDefinition: new SourcePatternModule(
    SourcePatternModuleKey.ExplicitResourceDefinition,
    SourcePatternModuleKind.ResourceDefinition,
    'Explicit resource definition',
    'Resource metadata is declared at the source site instead of relying on convention discovery.',
  ),
  RouterShell: new SourcePatternModule(
    SourcePatternModuleKey.RouterShell,
    SourcePatternModuleKind.RouterAdmission,
    'Router shell',
    'RouterConfiguration, route config, navigation links, and au-viewport shell wiring.',
  ),
  RouteContextSelection: new SourcePatternModule(
    SourcePatternModuleKey.RouteContextSelection,
    SourcePatternModuleKind.RouteContext,
    'Route-owned selection',
    'Route params, query values, fragments, or route-context reads own current item selection.',
  ),
  RouteParameterSelection: new SourcePatternModule(
    SourcePatternModuleKey.RouteParameterSelection,
    SourcePatternModuleKind.RouteContext,
    'Route parameter selection',
    'A route path parameter is the scalar identity for the current domain item or form request.',
  ),
  RouteLinkNavigation: new SourcePatternModule(
    SourcePatternModuleKey.RouteLinkNavigation,
    SourcePatternModuleKind.RouterAdmission,
    'Route link navigation',
    'Templates create static or data-driven route instructions instead of string-only DOM href plumbing.',
  ),
  NestedViewportLayout: new SourcePatternModule(
    SourcePatternModuleKey.NestedViewportLayout,
    SourcePatternModuleKind.RouterAdmission,
    'Nested viewport layout',
    'A child route area owns its own au-viewport so nested route components render inside the active parent route component.',
  ),
  DiStateBoundary: new SourcePatternModule(
    SourcePatternModuleKey.DiStateBoundary,
    SourcePatternModuleKind.DiBoundary,
    'DI state boundary',
    'Components resolve ordinary state/domain classes through Aurelia DI instead of passing facades around.',
  ),
  StateComposition: new SourcePatternModule(
    SourcePatternModuleKey.StateComposition,
    SourcePatternModuleKind.StateComposition,
    'State composition',
    'A state class owns typed child state/model instances rather than a flat object bag.',
  ),
  StateOwnedServiceBoundary: new SourcePatternModule(
    SourcePatternModuleKey.StateOwnedServiceBoundary,
    SourcePatternModuleKind.ServiceBoundary,
    'State-owned service boundary',
    'State owns service/repository calls for loading, saving, or submission side effects.',
  ),
  ServiceBackedLoading: new SourcePatternModule(
    SourcePatternModuleKey.ServiceBackedLoading,
    SourcePatternModuleKind.ServiceBoundary,
    'Service-backed loading',
    'State owns asynchronous loading/caching flags and calls an injected service or repository behind the template.',
  ),
  ServiceBackedSubmission: new SourcePatternModule(
    SourcePatternModuleKey.ServiceBackedSubmission,
    SourcePatternModuleKind.ServiceBoundary,
    'Service-backed submission',
    'State owns submit/save side effects and keeps templates calling state/domain behavior rather than services.',
  ),
  DomainClassModel: new SourcePatternModule(
    SourcePatternModuleKey.OrdinaryDomainClassModel,
    SourcePatternModuleKind.DomainModel,
    'Ordinary domain classes',
    'Domain entities and value objects are modeled as ordinary classes with readable properties and getters.',
  ),
  TemplateLocalDomainLookup: new SourcePatternModule(
    SourcePatternModuleKey.TemplateLocalDomainLookup,
    SourcePatternModuleKind.SelectionBoundary,
    'Template-local domain lookup',
    'A scalar identity is adapted to a nullable domain object in template scope before direct member binding.',
  ),
  NativeFormValueChannels: new SourcePatternModule(
    SourcePatternModuleKey.NativeFormValueChannels,
    SourcePatternModuleKind.FormValueChannel,
    'Native form value channels',
    'Native value, checked, select, option model, debounce, validate, or matcher channels carry form data flow.',
  ),
  NativeTextValueChannel: new SourcePatternModule(
    SourcePatternModuleKey.NativeTextValueChannel,
    SourcePatternModuleKind.FormValueChannel,
    'Native text value binding',
    'Text-like inputs and textareas use native value observers instead of manual input event synchronization.',
  ),
  CheckedBooleanChannel: new SourcePatternModule(
    SourcePatternModuleKey.CheckedBooleanChannel,
    SourcePatternModuleKind.FormValueChannel,
    'Checked boolean binding',
    'Boolean checkbox state flows through Aurelia checked observer semantics.',
  ),
  CheckedCollectionChannel: new SourcePatternModule(
    SourcePatternModuleKey.CheckedCollectionChannel,
    SourcePatternModuleKind.FormValueChannel,
    'Checked collection binding',
    'Array, Set, or Map membership flows through checked/model/value observer semantics.',
  ),
  SelectOptionModelChannel: new SourcePatternModule(
    SourcePatternModuleKey.SelectOptionModelChannel,
    SourcePatternModuleKind.FormValueChannel,
    'Select option model binding',
    'Select controls use option model values so domain values stay typed instead of stringly encoded.',
  ),
  SelectObjectMatcherChannel: new SourcePatternModule(
    SourcePatternModuleKey.SelectObjectMatcherChannel,
    SourcePatternModuleKind.FormValueChannel,
    'Select object matcher binding',
    'Object-valued select choices use an app-authored matcher when identity is domain-specific.',
  ),
  CollectionControls: new SourcePatternModule(
    SourcePatternModuleKey.CollectionControls,
    SourcePatternModuleKind.CollectionControls,
    'Collection controls',
    'Search, filter, sort, pagination, or selection state are owned by app state rather than DOM event plumbing.',
  ),
  SearchFilterControls: new SourcePatternModule(
    SourcePatternModuleKey.CollectionSearchFilterControls,
    SourcePatternModuleKind.CollectionControls,
    'Search/filter controls',
    'Search text and facet filters are state-owned collection controls, not ad hoc DOM handlers.',
  ),
  SortControls: new SourcePatternModule(
    SourcePatternModuleKey.CollectionSortControls,
    SourcePatternModuleKind.CollectionControls,
    'Sort controls',
    'Sort key/direction are explicit state so headers and derived rows stay coherent.',
  ),
  PaginationControls: new SourcePatternModule(
    SourcePatternModuleKey.CollectionPaginationControls,
    SourcePatternModuleKind.CollectionControls,
    'Pagination controls',
    'Page size, current page, and visible-row projection are state-owned collection behavior.',
  ),
  SelectionSetControls: new SourcePatternModule(
    SourcePatternModuleKey.CollectionSelectionSetControls,
    SourcePatternModuleKind.SelectionBoundary,
    'Selection set controls',
    'Selected IDs or values are held as a state-owned collection rather than coupled to row components.',
  ),
  ListRendering: new SourcePatternModule(
    SourcePatternModuleKey.ListRendering,
    SourcePatternModuleKind.ListRendering,
    'List rendering',
    'Repeated rows/cards/lists intentionally exercise item-scope template-controller handoff.',
  ),
  LocalObjectComponentBoundary: new SourcePatternModule(
    SourcePatternModuleKey.LocalObjectComponentBoundary,
    SourcePatternModuleKind.ComponentBoundary,
    'Local object component boundary',
    'A close parent/child component boundary may pass a typed domain object directly when that is the clean model.',
  ),
  ComponentBoundary: new SourcePatternModule(
    SourcePatternModuleKey.ComponentBoundary,
    SourcePatternModuleKind.ComponentBoundary,
    'Component boundary',
    'Component inputs or composition model handoffs are intentional app seams rather than accidental forwarding code.',
  ),
  CaptureAttributeFieldShell: new SourcePatternModule(
    SourcePatternModuleKey.CaptureAttributeFieldShell,
    SourcePatternModuleKind.ComponentBoundary,
    'Captured field-shell attributes',
    'Wrapper form components capture and forward native attributes/bindings through ...$attrs without becoming value facades.',
  ),
  TemplateControllerFlow: new SourcePatternModule(
    SourcePatternModuleKey.TemplateControllerFlow,
    SourcePatternModuleKind.TemplateController,
    'Template-controller flow',
    'If, repeat, switch, promise, or let scopes are intentional semantic structure rather than markup decoration.',
  ),
  ClassStyleChannels: new SourcePatternModule(
    SourcePatternModuleKey.ClassStyleChannels,
    SourcePatternModuleKind.StyleBinding,
    'Class/style binding channels',
    'Class and style bindings exercise binding channels without making the reference CSS a design-system policy.',
  ),
  I18nPlugin: new SourcePatternModule(
    SourcePatternModuleKey.I18nPlugin,
    SourcePatternModuleKind.PluginIntegration,
    'i18n plugin integration',
    '@aurelia/i18n configuration and translation bindings are part of the app-building source shape.',
  ),
  PluginIntegration: new SourcePatternModule(
    SourcePatternModuleKey.PluginIntegration,
    SourcePatternModuleKind.PluginIntegration,
    'Plugin integration',
    'A framework or community plugin configuration is an intentional source capability rather than incidental source.',
  ),
  ValidationPlugin: new SourcePatternModule(
    SourcePatternModuleKey.ValidationPlugin,
    SourcePatternModuleKind.PluginIntegration,
    'Validation plugin integration',
    '@aurelia/validation-html configuration, rules, validate bindings, and validation errors are part of the app-building source shape.',
  ),
  DynamicComposition: new SourcePatternModule(
    SourcePatternModuleKey.DynamicComponentComposition,
    SourcePatternModuleKind.DynamicComposition,
    'Dynamic component composition',
    'au-compose component/template/model handoff is intentional dynamic composition structure.',
  ),
  StateStorePlugin: new SourcePatternModule(
    SourcePatternModuleKey.AureliaStateStore,
    SourcePatternModuleKind.StateStore,
    '@aurelia/state store',
    '@aurelia/state store configuration, actions, and state binding command semantics are the state model.',
  ),
} as const;
