import type { SourcePlanProjectTooling } from './package-tooling.js';

/** Source language family for a planned source artifact. */
export enum SourcePlanLanguage {
  /** TypeScript source file. */
  TypeScript = 'typescript',
  /** HTML template source file. */
  Html = 'html',
  /** JSON configuration or manifest source file. */
  Json = 'json',
  /** CSS stylesheet source file. */
  Css = 'css',
  /** Plain text source artifact. */
  Text = 'text',
}

/** App-topology role a source file plays after the edit is applied. */
export enum SourcePlanFileRole {
  /** Application entrypoint that boots Aurelia. */
  Entrypoint = 'entrypoint',
  /** Root component view-model. */
  RootComponent = 'root-component',
  /** Non-root component view-model. */
  Component = 'component',
  /** HTML template owned by a component or route. */
  Template = 'template',
  /** Component-scoped stylesheet. */
  ComponentStyle = 'component-style',
  /** Application-level stylesheet. */
  GlobalStyle = 'global-style',
  /** DI-injectable state or store model. */
  StateModel = 'state-model',
  /** Domain entity or value-object model. */
  DomainModel = 'domain-model',
  /** Service, repository, or adapter boundary. */
  Service = 'service',
  /** Project configuration or package tooling file. */
  ProjectConfig = 'project-config',
  /** File whose topology role is intentionally not modeled yet. */
  Other = 'other',
}

/** File-level edit shape before a host resolves conflicts or formatting. */
export enum SourcePlanEditKind {
  /** Create a file that should not already exist. */
  Create = 'create',
  /** Replace an existing file. */
  Replace = 'replace',
  /** Create or replace depending on host policy. */
  Upsert = 'upsert',
}

/** Caller-owned opaque operation key associated with a planned file, when an upstream planner owns one. */
export type SourcePlanOperationKind = string;

/** Who owns the concrete text in this source plan. */
export enum SourcePlanTextAuthority {
  /** Semantic-runtime produced this as canonical recipe output. */
  SemanticRuntimeRecipe = 'semantic-runtime-recipe',
  /** App-builder produced complete source text from an app-building workflow. */
  AppBuilderGenerated = 'app-builder-generated',
  /** Semantic-runtime produced this as a complete reference instantiation of a reusable pattern. */
  SemanticRuntimeReferenceInstantiation = 'semantic-runtime-reference-instantiation',
  /** The host or AI must produce the concrete text from semantic contracts. */
  HostOwned = 'host-owned',
  /** A human/operator supplied the exact text. */
  OperatorSupplied = 'operator-supplied',
}

/** Conflict policy is explicit so edit application never hides overwrite behavior. */
export enum SourcePlanConflictPolicy {
  /** The host should fail if the target file already exists. */
  MustNotExist = 'must-not-exist',
  /** A file previously generated by this substrate may be replaced. */
  ReplaceGeneratedFile = 'replace-generated-file',
  /** The host owns conflict resolution. */
  HostDecides = 'host-decides',
}

/** Formatting policy is explicit because semantic-runtime should not silently own project style. */
export enum SourcePlanFormattingPolicy {
  /** Formatting follows a legacy recipe baseline. */
  RecipeBaseline = 'recipe-baseline',
  /** Formatting follows the app-builder source baseline. */
  AppBuilderBaseline = 'app-builder-baseline',
  /** The host formatter should own final formatting. */
  HostFormatter = 'host-formatter',
  /** A human/operator decides formatting. */
  OperatorDecides = 'operator-decides',
}

/** Package/build policy remains separate from source files. */
export enum SourcePlanPackageToolingPolicy {
  /** Package and build tooling are not modeled by this source plan. */
  NotModeled = 'not-modeled',
  /** The host owns package and build tooling. */
  HostOwned = 'host-owned',
  /** Package and build tooling follow a recipe/source-plan baseline. */
  RecipeBaseline = 'recipe-baseline',
}

/** How recipe-owned source text relates to the caller's actual domain model. */
export enum SourcePatternDomainModelPolicy {
  /** The source text is an app-shell or framework pattern with no meaningful sample domain nouns. */
  DomainNeutral = 'domain-neutral',
  /** The source text already reflects caller-supplied domain identity and can be used as a domain-specific start. */
  CallerApplied = 'caller-applied',
  /** The source text is a complete reference instantiation; callers should rename/remap its sample domain. */
  ReferenceInstantiation = 'reference-instantiation',
  /** The host or AI must provide the concrete domain model before source text should be emitted as app code. */
  HostDomainRequired = 'host-domain-required',
}

/** Who owns presentation decisions such as layout, spacing, density, and visual tokens. */
export enum SourcePatternStylePolicy {
  /** No authored style surface is present. */
  None = 'none',
  /** Only structural style needed to make the framework/API pattern readable is modeled. */
  StructuralBaseline = 'structural-baseline',
  /** Concrete CSS is a reference fixture/example and should be adapted or replaced by the host. */
  ReferencePresentation = 'reference-presentation',
  /** The host owns all visual styling decisions. */
  HostOwned = 'host-owned',
}

/** What kind of artifact this source pattern should be treated as by source-generation clients. */
export enum SourcePatternRole {
  /** Public recipe output that is intended to be a recommendable starting point for app source. */
  RecommendableRecipe = 'recommendable-recipe',
  /** Focused reusable capability example that should be merged into another recipe rather than scaffolded wholesale. */
  PatternReference = 'pattern-reference',
  /** Complete concrete scenario used for transfer/verification; adapt nouns, data, and presentation before app use. */
  ScenarioReference = 'scenario-reference',
  /** Dense analyzer-pressure artifact; useful for semantic-runtime coverage but not a public app-building recommendation. */
  StressFixture = 'stress-fixture',
}

/** How concrete records/defaults inside a source pattern relate to caller data. */
export enum SourcePatternDataPolicy {
  /** No seed data or mock records are part of the pattern. */
  None = 'none',
  /** Data shape is a service/state contract and caller data should arrive through that boundary. */
  ServiceContract = 'service-contract',
  /** Small generated seed records follow caller source parameters and exist only to make the starter runnable. */
  StarterSampleData = 'starter-sample-data',
  /** Small synthetic records are included only to make the scenario runnable and analyzable. */
  SyntheticReferenceData = 'synthetic-reference-data',
  /** Caller or host must provide the data shape before source should be emitted as application code. */
  CallerSupplied = 'caller-supplied',
}

/** Why the source text has its current verbosity/density. */
export enum SourcePatternCodeEconomyPolicy {
  /** Code is intended to be terse production-style Aurelia. */
  ProductionTerse = 'production-terse',
  /** Code is explicit for teaching or transfer and may be trimmed in a real app. */
  TeachingExplicit = 'teaching-explicit',
  /** Code is complete enough to reopen and verify a scenario end-to-end. */
  ReferenceComplete = 'reference-complete',
  /** Code is deliberately dense to pressure semantic-runtime rather than to model user-facing style. */
  PressureRich = 'pressure-rich',
}

/** Public client action for source text carried by a source pattern. */
export enum SourcePatternUsePolicy {
  /** The concrete source is intended to be used as the caller's starting scaffold. */
  ApplyAsSourceStart = 'apply-as-source-start',
  /** The concrete source proves a scenario, but caller-domain code must adapt nouns, data, copy, and presentation. */
  AdaptBeforeEmitting = 'adapt-before-emitting',
  /** The concrete source is a companion capability reference; merge relevant pieces into a primary plan. */
  MergeSelectively = 'merge-selectively',
  /** The concrete source is semantic-runtime pressure only and should not be emitted as user app code. */
  AnalysisPressureOnly = 'analysis-pressure-only',
}

/** Reusable adaptation slot exposed by a source pattern. */
export enum SourcePatternParameterKind {
  /** Primary domain class or aggregate that the reference instantiation names concretely. */
  DomainEntity = 'domain-entity',
  /** Caller-owned member/field schema for forms, tables, cards, details, validation, and derived labels. */
  FieldSchema = 'field-schema',
  /** Collection, option set, action set, or repeated domain surface that must move with the entity model. */
  DomainCollection = 'domain-collection',
  /** Scalar identity used for current-object selection independent of any router involvement. */
  SelectionIdentity = 'selection-identity',
  /** Route path/query/fragment identity that must stay aligned with router config and route-context reads. */
  RouteIdentity = 'route-identity',
  /** User-visible labels, titles, and navigation copy that belong to the caller's feature vocabulary. */
  FeatureCopy = 'feature-copy',
  /** Inline records or defaults included to make the reference instantiation runnable and analyzable. */
  SampleData = 'sample-data',
  /** CSS, layout names, or visual tokens included as reference presentation rather than recipe ontology. */
  Presentation = 'presentation',
}

/** Expected caller value shape for a source-pattern parameter. */
export enum SourcePatternParameterValueShape {
  /** Human domain noun phrase such as "Support Ticket"; recipe code may derive identifiers from it. */
  DomainTitle = 'domain-title',
  /** Lower/upper source identifier member, variable, method, property, or scalar ID name. */
  SourceMemberName = 'source-member-name',
  /** Router path text such as "support-tickets" or "support-tickets/:supportTicketId". */
  RoutePath = 'route-path',
  /** Router parameter identifier such as "supportTicketId". */
  RouteParameterName = 'route-parameter-name',
  /** User-visible route title or navigation label. */
  RouteTitle = 'route-title',
  /** Comma-separated static route section labels such as "Account, Billing, API Keys". */
  RouteSectionList = 'route-section-list',
  /** Comma-separated workflow/wizard step labels such as "Details, Billing, Review". */
  WorkflowStepList = 'workflow-step-list',
  /** Semicolon-separated named workflow section fields such as `Shipping: address; Payment: payment method select`. */
  WorkflowSectionFieldSchemaList = 'workflow-section-field-schema-list',
  /** Comma-separated field/control descriptors that still need a recipe-owned schema model before full source rewriting. */
  FieldSchemaList = 'field-schema-list',
  /** Semicolon-separated option groups such as `roles: admin, editor; permissions: read, write`. */
  OptionSchemaList = 'option-schema-list',
  /** Human summary of option sets, repeated collections, or domain-owned action groups. */
  DomainCollectionSummary = 'domain-collection-summary',
  /** Human-visible copy or label text owned by the caller's feature vocabulary. */
  CopyText = 'copy-text',
  /** Human summary of synthetic records or defaults included only to make a reference instantiation runnable. */
  SampleDataSummary = 'sample-data-summary',
  /** Human summary of CSS/layout/tokens that should be adapted to the host design surface. */
  PresentationSummary = 'presentation-summary',
  /** Deliberately loose value used while a more specific source-pattern parameter is being designed. */
  FreeformSummary = 'freeform-summary',
}

/** Reusable semantic source-pattern capability that may appear in many recipes or fixtures. */
export enum SourcePatternModuleKind {
  /** Root app source, entrypoint, root component, or external template shell. */
  AppShell = 'app-shell',
  /** Convention-based resource admission instead of explicit component metadata. */
  ResourceConvention = 'resource-convention',
  /** RouterConfiguration, route config, navigation links, or au-viewport shell wiring. */
  RouterAdmission = 'router-admission',
  /** RouteContext, route parameters, query values, fragments, or route-owned selection handoff. */
  RouteContext = 'route-context',
  /** DI-resolved state/service/model boundary visible to templates or components. */
  DiBoundary = 'di-boundary',
  /** Ordinary class state composed from child state/model instances. */
  StateComposition = 'state-composition',
  /** Service/repository boundary owned by state for loading or submission side effects. */
  ServiceBoundary = 'service-boundary',
  /** Caller domain model, entity type, value object, or derived domain getter. */
  DomainModel = 'domain-model',
  /** Native input/select/checked/matcher/value binding channels. */
  FormValueChannel = 'form-value-channel',
  /** Search, filter, sort, pagination, or selection controls over a collection. */
  CollectionControls = 'collection-controls',
  /** Repeated rows/cards/lists and item-scope template-controller handoff. */
  ListRendering = 'list-rendering',
  /** Scalar or object identity boundary for selecting a current domain item. */
  SelectionBoundary = 'selection-boundary',
  /** Parent-to-child custom-element handoff through bindables, capture/spread, or local object APIs. */
  ComponentBoundary = 'component-boundary',
  /** If/repeat/switch/promise template-controller semantics intentionally exercised by source. */
  TemplateController = 'template-controller',
  /** Class/style binding channels, not broad design-system ownership. */
  StyleBinding = 'style-binding',
  /** Plugin configuration such as i18n, validation-html, router, or state. */
  PluginIntegration = 'plugin-integration',
  /** Dynamic component/template/model composition through au-compose. */
  DynamicComposition = 'dynamic-composition',
  /** @aurelia/state store, action, and state binding-command semantics. */
  StateStore = 'state-store',
}

/** Reusable source-pattern module identity. */
export enum SourcePatternModuleKey {
  /** Aurelia entrypoint plus root component/template shell. */
  AureliaAppShell = 'aurelia-app-shell',
  /** Convention-based resource discovery. */
  ConventionResourceAdmission = 'convention-resource-admission',
  /** Router configuration and viewport shell. */
  RouterShell = 'router-shell',
  /** Route context owns current selection. */
  RouteContextSelection = 'route-context-selection',
  /** Route path parameter owns current selection. */
  RouteParameterSelection = 'route-parameter-selection',
  /** Templates produce route instructions. */
  RouteLinkNavigation = 'route-link-navigation',
  /** Aurelia DI owns state access. */
  DiStateBoundary = 'di-state-boundary',
  /** State composes nested state/model instances. */
  StateComposition = 'state-composition',
  /** State owns service/repository boundary. */
  StateOwnedServiceBoundary = 'state-owned-service-boundary',
  /** State owns async loading behavior. */
  ServiceBackedLoading = 'service-backed-loading',
  /** State owns submit/save side effects. */
  ServiceBackedSubmission = 'service-backed-submission',
  /** Ordinary domain class modeling. */
  OrdinaryDomainClassModel = 'ordinary-domain-class-model',
  /** Template adapts scalar identity to domain object. */
  TemplateLocalDomainLookup = 'template-local-domain-lookup',
  /** Native form observer channels. */
  NativeFormValueChannels = 'native-form-value-channels',
  /** Text value observer channel. */
  NativeTextValueChannel = 'native-text-value-channel',
  /** Boolean checked observer channel. */
  CheckedBooleanChannel = 'checked-boolean-channel',
  /** Collection checked observer channel. */
  CheckedCollectionChannel = 'checked-collection-channel',
  /** Option-model select channel. */
  SelectOptionModelChannel = 'select-option-model-channel',
  /** Object matcher select channel. */
  SelectObjectMatcherChannel = 'select-object-matcher-channel',
  /** Collection control state. */
  CollectionControls = 'collection-controls',
  /** Search/filter collection controls. */
  CollectionSearchFilterControls = 'collection-search-filter-controls',
  /** Sort collection controls. */
  CollectionSortControls = 'collection-sort-controls',
  /** Pagination collection controls. */
  CollectionPaginationControls = 'collection-pagination-controls',
  /** Selection-set collection controls. */
  CollectionSelectionSetControls = 'collection-selection-set-controls',
  /** Repeated list rendering. */
  ListRendering = 'list-rendering',
  /** Close parent/child object component boundary. */
  LocalObjectComponentBoundary = 'local-object-component-boundary',
  /** General component boundary. */
  ComponentBoundary = 'component-boundary',
  /** Attribute-capturing field-shell boundary. */
  CaptureAttributeFieldShell = 'capture-attribute-field-shell',
  /** Template-controller control flow. */
  TemplateControllerFlow = 'template-controller-flow',
  /** Class/style binding channels. */
  ClassStyleChannels = 'class-style-channels',
  /** i18n plugin integration. */
  I18nPlugin = 'i18n-plugin',
  /** Generic plugin integration. */
  PluginIntegration = 'plugin-integration',
  /** Validation plugin integration. */
  ValidationPlugin = 'validation-plugin',
  /** Dynamic component composition. */
  DynamicComponentComposition = 'dynamic-component-composition',
  /** @aurelia/state store integration. */
  AureliaStateStore = 'aurelia-state-store',
}

/** Reusable adaptation parameter identity. */
export enum SourcePatternParameterKey {
  /** Detail route parameter name shared by route config, route context, and navigation source. */
  DetailRouteParameter = 'detail-route-parameter',
  /** List route path shared by route config and navigation source. */
  ListRoutePath = 'list-route-path',
}

/** Adaptation group identity for related source-pattern parameters. */
export enum SourcePatternAdaptationGroupKey {
  /** Route path and parameter identity must move together. */
  RouteIdentity = 'route-identity',
}

/** How far semantic-runtime can currently carry a source-pattern parameter into emitted artifacts. */
export enum SourcePatternParameterApplicationPolicy {
  /** The parameter is a marker for AI/host adaptation; semantic-runtime does not rewrite source for it yet. */
  AdvisoryOnly = 'advisory-only',
  /** The parameter has a recipe-owned source application that changes generated source text. */
  SourceTextInput = 'source-text-input',
}

/** Outcome for a caller-supplied source-pattern value on a source-plan request. */
export enum SourcePatternParameterApplicationState {
  /** The value matched a parameter whose policy lets semantic-runtime apply it to this source plan. */
  AppliedToSourcePlan = 'applied-to-source-plan',
  /** The value matched a source-applicable parameter, but the built source plan did not reflect the requested value. */
  NotAppliedToSourcePlan = 'not-applied-to-source-plan',
  /** The value matched an advisory marker; the host/AI must adapt concrete source manually. */
  AdvisoryOnly = 'advisory-only',
  /** The value named no parameter on the selected source pattern. */
  UnknownParameter = 'unknown-parameter',
}

/** Reusable source-pattern module metadata. */
export class SourcePatternModule {
  constructor(
    readonly key: SourcePatternModuleKey,
    readonly kind: SourcePatternModuleKind,
    readonly title: string,
    readonly summary: string,
  ) {}
}

/** Parameter cluster that should be considered together when adapting a reference instantiation. */
export class SourcePatternAdaptationGroup {
  constructor(
    readonly key: SourcePatternAdaptationGroupKey,
    readonly title: string,
    readonly summary: string,
    readonly parameterKeys: readonly SourcePatternParameterKey[],
  ) {}
}

/** Reusable adaptation parameter exposed by a source pattern. */
export class SourcePatternParameter {
  constructor(
    readonly key: SourcePatternParameterKey,
    readonly kind: SourcePatternParameterKind,
    readonly applicationPolicy: SourcePatternParameterApplicationPolicy,
    readonly valueShape: SourcePatternParameterValueShape,
    readonly title: string,
    readonly defaultValue: string | null,
    readonly summary: string,
  ) {}
}

export interface SourcePatternParameterValue {
  readonly key: SourcePatternParameterKey;
  readonly value: string;
}

/** Reusable source pattern metadata, separate from a particular fixture/default instantiation. */
export class SourcePattern {
  readonly kind = 'source-pattern' as const;

  constructor(
    readonly key: string,
    readonly title: string,
    readonly summary: string,
    readonly role: SourcePatternRole,
    readonly domainModelPolicy: SourcePatternDomainModelPolicy,
    readonly stylePolicy: SourcePatternStylePolicy,
    readonly dataPolicy: SourcePatternDataPolicy,
    readonly codeEconomyPolicy: SourcePatternCodeEconomyPolicy,
    readonly adaptationNotes: readonly string[],
    readonly parameters: readonly SourcePatternParameter[] = [],
    readonly modules: readonly SourcePatternModule[] = [],
    readonly adaptationGroups: readonly SourcePatternAdaptationGroup[] = [],
  ) {}
}

export function sourcePatternUsePolicy(
  pattern: Pick<SourcePattern, 'role' | 'domainModelPolicy' | 'stylePolicy' | 'dataPolicy' | 'codeEconomyPolicy'>,
): SourcePatternUsePolicy {
  if (
    pattern.role === SourcePatternRole.StressFixture
    || pattern.codeEconomyPolicy === SourcePatternCodeEconomyPolicy.PressureRich
  ) {
    return SourcePatternUsePolicy.AnalysisPressureOnly;
  }
  if (pattern.role === SourcePatternRole.PatternReference) {
    return SourcePatternUsePolicy.MergeSelectively;
  }
  if (
    pattern.role === SourcePatternRole.ScenarioReference
    || pattern.domainModelPolicy === SourcePatternDomainModelPolicy.ReferenceInstantiation
    || pattern.stylePolicy === SourcePatternStylePolicy.ReferencePresentation
    || pattern.dataPolicy === SourcePatternDataPolicy.SyntheticReferenceData
    || pattern.codeEconomyPolicy === SourcePatternCodeEconomyPolicy.ReferenceComplete
  ) {
    return SourcePatternUsePolicy.AdaptBeforeEmitting;
  }
  return SourcePatternUsePolicy.ApplyAsSourceStart;
}

export function sourcePatternUseSummary(
  pattern: Pick<SourcePattern, 'role' | 'domainModelPolicy' | 'stylePolicy' | 'dataPolicy' | 'codeEconomyPolicy'>,
): string {
  switch (sourcePatternUsePolicy(pattern)) {
    case SourcePatternUsePolicy.ApplyAsSourceStart:
      return 'Concrete source is a recommendable starting scaffold unless an existing app already owns that structure.';
    case SourcePatternUsePolicy.AdaptBeforeEmitting:
      return 'Concrete source is transfer material; adapt caller domain names, data defaults, copy, and presentation before emitting app code.';
    case SourcePatternUsePolicy.MergeSelectively:
      return 'Concrete source is a companion capability reference; merge only the relevant modules and semantic promises into the primary plan.';
    case SourcePatternUsePolicy.AnalysisPressureOnly:
      return 'Concrete source is analyzer pressure and should not be emitted as public app code.';
  }
}

function defaultSourcePatternParameterValueShape(
  kind: SourcePatternParameterKind,
): SourcePatternParameterValueShape {
  switch (kind) {
    case SourcePatternParameterKind.DomainEntity:
      return SourcePatternParameterValueShape.DomainTitle;
    case SourcePatternParameterKind.SelectionIdentity:
      return SourcePatternParameterValueShape.SourceMemberName;
    case SourcePatternParameterKind.RouteIdentity:
      return SourcePatternParameterValueShape.RoutePath;
    case SourcePatternParameterKind.FieldSchema:
      return SourcePatternParameterValueShape.FieldSchemaList;
    case SourcePatternParameterKind.DomainCollection:
      return SourcePatternParameterValueShape.DomainCollectionSummary;
    case SourcePatternParameterKind.FeatureCopy:
      return SourcePatternParameterValueShape.CopyText;
    case SourcePatternParameterKind.SampleData:
      return SourcePatternParameterValueShape.SampleDataSummary;
    case SourcePatternParameterKind.Presentation:
      return SourcePatternParameterValueShape.PresentationSummary;
  }
}

/** Concrete file text, when a producer can emit it without another policy decision. */
export class SourcePlanText {
  readonly kind = 'source-plan-text' as const;

  constructor(
    readonly text: string,
    readonly authority: SourcePlanTextAuthority,
  ) {}
}

/** Policy envelope for applying a source edit plan. */
export class SourcePlanPolicy {
  readonly kind = 'source-plan-policy' as const;

  constructor(
    readonly conflictPolicy: SourcePlanConflictPolicy,
    readonly formattingPolicy: SourcePlanFormattingPolicy,
    readonly packageToolingPolicy: SourcePlanPackageToolingPolicy,
  ) {}
}

/** One file-level source artifact requested by a source plan. */
export class SourcePlanFile {
  readonly kind = 'source-plan-file' as const;

  constructor(
    readonly path: string,
    readonly role: SourcePlanFileRole,
    readonly language: SourcePlanLanguage,
    readonly editKind: SourcePlanEditKind,
    readonly operationKind: SourcePlanOperationKind | null,
    readonly text: SourcePlanText | null,
  ) {}
}

/** Planned source artifacts before a host writes files or resolves conflicts. */
export class SourcePlan {
  readonly kind = 'source-plan' as const;

  constructor(
    readonly rootDir: string,
    readonly policy: SourcePlanPolicy,
    readonly files: readonly SourcePlanFile[],
    /** Structured package/typecheck artifacts that are applied beside app source, when the recipe owns them. */
    readonly projectTooling: SourcePlanProjectTooling | null = null,
    /** Pattern/default-instantiation metadata so clients do not mistake sample domains for recipe ontology. */
    readonly pattern: SourcePattern | null = null,
  ) {}

  get hasCompleteFileText(): boolean {
    return this.files.every((file) => file.text != null)
      && (this.projectTooling?.hasCompleteFileText ?? true);
  }
}

export function recipeSourceEditPolicy(
  packageToolingPolicy: SourcePlanPackageToolingPolicy = SourcePlanPackageToolingPolicy.NotModeled,
): SourcePlanPolicy {
  return new SourcePlanPolicy(
    SourcePlanConflictPolicy.MustNotExist,
    SourcePlanFormattingPolicy.RecipeBaseline,
    packageToolingPolicy,
  );
}

export function sourcePlanHasCompleteText(
  sourcePlan: SourcePlan,
): boolean {
  return sourcePlan.hasCompleteFileText;
}

export function referenceInstantiationSourceFiles(
  files: readonly SourcePlanFile[],
): readonly SourcePlanFile[] {
  return files.map((file) => sourceFileWithTextAuthority(
    file,
    SourcePlanTextAuthority.SemanticRuntimeReferenceInstantiation,
  ));
}

export function sourceFileWithTextAuthority(
  file: SourcePlanFile,
  textAuthority: SourcePlanTextAuthority,
): SourcePlanFile {
  return new SourcePlanFile(
    file.path,
    file.role,
    file.language,
    file.editKind,
    file.operationKind,
    file.text == null
      ? null
      : new SourcePlanText(file.text.text, textAuthority),
  );
}
