export {
  TextSpan,
  SourceSpan,
  normalizeSpan,
  spanFromBounds,
  sourceSpanFromBounds,
  offsetSpan,
  absoluteSpan,
  ensureSpanFile,
  type SpanLike,
} from '../source-address.js';
export {
  Identifier,
  BindingBehaviorExpression,
  ValueConverterExpression,
  AssignExpression,
  ConditionalExpression,
  AccessGlobalExpression,
  AccessThisExpression,
  AccessBoundaryExpression,
  AccessScopeExpression,
  AccessMemberExpression,
  AccessKeyedExpression,
  ParenExpression,
  NewExpression,
  CallScopeExpression,
  CallMemberExpression,
  CallFunctionExpression,
  CallGlobalExpression,
  BinaryExpression,
  UnaryExpression,
  PrimitiveLiteralExpression,
  ArrayLiteralExpression,
  ObjectLiteralExpression,
  TemplateExpression,
  TaggedTemplateExpression,
  BindingIdentifier,
  ForOfStatement,
  Interpolation,
  BindingPatternDefault,
  BindingPatternHole,
  ArrayBindingPattern,
  ObjectBindingPattern,
  ObjectBindingPatternProperty,
  DestructuringAssignmentExpression,
  ArrowFunction,
  CustomExpression,
} from './ast.js';
export {
  ExpressionParser,
  type ExpressionParseContext,
} from './expression-parser.js';
export {
  ExpressionParseSelectionKind,
  SelectedExpressionEntryFamily,
  NoParseSelection,
  ExpressionParseRequest,
} from './parse-selection.js';
export {
  Scanner,
  Token,
  TokenType,
  TokenFlags,
  hasTokenFlag,
  tokenFlags,
  tokenTypeName,
  CharCode,
} from './expression-scanner.js';
export {
  ExpressionParseResultKind,
  ExpressionParseResultFlags,
  ExpressionFrontierKind,
  ExpressionExpectedContinuationClass,
  ExpressionCompanionFrameKind,
  ExpressionGapKind,
  MatchedDelimiterKind,
  IteratorActiveRegionKind,
  IteratorOfSeparatorStateKind,
  IteratorTrailingSplitKind,
  InterpolationHoleBoundaryKind,
  InterpolationSuppressedHolePublicationKind,
  expressionParseResultKindFlags,
  hasExpressionParseResultKindFlag,
  MatchedDelimiterEntry,
  ClosedSubtreeRef,
  ExpressionGapDescriptor,
  IteratorOfSeparatorState,
  IteratorTrailingSplitState,
  ExpressionSuccess,
  EmptyExpressionSuccess,
  IteratorSuccess,
  InterpolationSuccess,
  InterpolationAbsent,
  OpaqueSuccess,
  NoExpressionParse,
  CompleteInputParseError,
  PropertyLikeDegradedPublication,
  PropertyLikeFrontierPublication,
  IteratorDegradedPublication,
  IteratorFrontierPublication,
  InterpolationClosedHole,
  InterpolationHoleBoundaryState,
  InterpolationActiveHoleCompanion,
  InterpolationSuppressedHole,
  InterpolationDegradedPublication,
  InterpolationFrontierPublication,
} from './parse-result-algebra.js';
export { ExpressionParseResultInspector } from './parse-result-inspection.js';
export type {
  AnyBindingExpression,
  AssignmentOperator,
  BinaryOperator,
  ExpressionAstNode,
  ExpressionType,
  IsBindingBehavior,
  IsExpression,
  IsLeftHandSide,
  IsPrimary,
  IsUnary,
  IsBinary,
  IsConditional,
  IsAssign,
  IsValueConverter,
  BindingPattern,
  BindingIdentifierOrPattern,
  IsAssignable,
  UnaryOperator,
} from './ast.js';
export type {
  CompanionExpressionParseResult,
  CompletedExpressionParseResult,
  NonOwningExpressionParseResult,
  CompletedInputBindingExpression,
  CompletedInputExpressionNode,
  CompletedInputPropertyLikeExpression,
  EmptyExpressionAst,
  ExpressionParseResult,
  ExpressionParseResultPublisher,
  PropertyLikeParseResult,
  IteratorParseResult,
  InterpolationParseResult,
  CustomParseResult,
  PropertyLikeEntryFamily,
} from './parse-result-algebra.js';
export type {
  ExpressionParseSelection,
} from './parse-selection.js';
