export {
  BOUNDED_REFERENCE_SEED_KINDS,
  findNodeBySpan,
  guessScriptKind,
  hasStaticModifier,
  readCallCalleeText,
  readPropertyName,
  readReferenceName,
  readReferenceSeed,
  readStringArrayValues,
  readStringLiteralValue,
  unwrapExpression,
  type BoundedReferenceSeed,
  type BoundedReferenceSeedKind,
} from './ts-ast-helpers.js';
