import { sourcePatternModule } from './source-plan.js';

/** Shared source-pattern modules used to describe reusable recipe architecture without copying scenario nouns. */
export const SourcePatternModules = {
  AppShell: sourcePatternModule(
    'aurelia-app-shell',
    'app-shell',
    'Aurelia app shell',
    'Public Aurelia entrypoint plus root component/template ownership.',
  ),
  ConventionResource: sourcePatternModule(
    'convention-resource-admission',
    'resource-convention',
    'Convention resource admission',
    'Class/file/template naming is intentionally compatible with Aurelia convention resource discovery.',
  ),
  RouterShell: sourcePatternModule(
    'router-shell',
    'router-admission',
    'Router shell',
    'RouterConfiguration, route config, navigation links, and au-viewport shell wiring.',
  ),
  RouteContextSelection: sourcePatternModule(
    'route-context-selection',
    'route-context',
    'Route-owned selection',
    'Route params, query values, fragments, or route-context reads own current item selection.',
  ),
  RouteParameterSelection: sourcePatternModule(
    'route-parameter-selection',
    'route-context',
    'Route parameter selection',
    'A route path parameter is the scalar identity for the current domain item or form request.',
  ),
  RouteLinkNavigation: sourcePatternModule(
    'route-link-navigation',
    'router-admission',
    'Route link navigation',
    'Templates create static or data-driven route instructions instead of string-only DOM href plumbing.',
  ),
  DiStateBoundary: sourcePatternModule(
    'di-state-boundary',
    'di-boundary',
    'DI state boundary',
    'Components resolve ordinary state/domain classes through Aurelia DI instead of passing facades around.',
  ),
  StateComposition: sourcePatternModule(
    'state-composition',
    'state-composition',
    'State composition',
    'A state class owns typed child state/model instances rather than a flat object bag.',
  ),
  StateOwnedServiceBoundary: sourcePatternModule(
    'state-owned-service-boundary',
    'service-boundary',
    'State-owned service boundary',
    'State owns service/repository calls for loading, saving, or submission side effects.',
  ),
  ServiceBackedLoading: sourcePatternModule(
    'service-backed-loading',
    'service-boundary',
    'Service-backed loading',
    'State owns asynchronous loading/caching flags and calls an injected service or repository behind the template.',
  ),
  ServiceBackedSubmission: sourcePatternModule(
    'service-backed-submission',
    'service-boundary',
    'Service-backed submission',
    'State owns submit/save side effects and keeps templates calling state/domain behavior rather than services.',
  ),
  DomainClassModel: sourcePatternModule(
    'ordinary-domain-class-model',
    'domain-model',
    'Ordinary domain classes',
    'Domain entities and value objects are modeled as ordinary classes with readable properties and getters.',
  ),
  TemplateLocalDomainLookup: sourcePatternModule(
    'template-local-domain-lookup',
    'selection-boundary',
    'Template-local domain lookup',
    'A scalar identity is adapted to a nullable domain object in template scope before direct member binding.',
  ),
  NativeFormValueChannels: sourcePatternModule(
    'native-form-value-channels',
    'form-value-channel',
    'Native form value channels',
    'Native value, checked, select, option model, debounce, validate, or matcher channels carry form data flow.',
  ),
  NativeTextValueChannel: sourcePatternModule(
    'native-text-value-channel',
    'form-value-channel',
    'Native text value binding',
    'Text-like inputs and textareas use native value observers instead of manual input event synchronization.',
  ),
  CheckedBooleanChannel: sourcePatternModule(
    'checked-boolean-channel',
    'form-value-channel',
    'Checked boolean binding',
    'Boolean checkbox state flows through Aurelia checked observer semantics.',
  ),
  CheckedCollectionChannel: sourcePatternModule(
    'checked-collection-channel',
    'form-value-channel',
    'Checked collection binding',
    'Array, Set, or Map membership flows through checked/model/value observer semantics.',
  ),
  SelectOptionModelChannel: sourcePatternModule(
    'select-option-model-channel',
    'form-value-channel',
    'Select option model binding',
    'Select controls use option model values so domain values stay typed instead of stringly encoded.',
  ),
  SelectObjectMatcherChannel: sourcePatternModule(
    'select-object-matcher-channel',
    'form-value-channel',
    'Select object matcher binding',
    'Object-valued select choices use an app-authored matcher when identity is domain-specific.',
  ),
  CollectionControls: sourcePatternModule(
    'collection-controls',
    'collection-controls',
    'Collection controls',
    'Search, filter, sort, pagination, or selection state are owned by app state rather than DOM event plumbing.',
  ),
  SearchFilterControls: sourcePatternModule(
    'collection-search-filter-controls',
    'collection-controls',
    'Search/filter controls',
    'Search text and facet filters are state-owned collection controls, not ad hoc DOM handlers.',
  ),
  SortControls: sourcePatternModule(
    'collection-sort-controls',
    'collection-controls',
    'Sort controls',
    'Sort key/direction are explicit state so headers and derived rows stay coherent.',
  ),
  PaginationControls: sourcePatternModule(
    'collection-pagination-controls',
    'collection-controls',
    'Pagination controls',
    'Page size, current page, and visible-row projection are state-owned collection behavior.',
  ),
  SelectionSetControls: sourcePatternModule(
    'collection-selection-set-controls',
    'selection-boundary',
    'Selection set controls',
    'Selected IDs or values are held as a state-owned collection rather than coupled to row components.',
  ),
  ListRendering: sourcePatternModule(
    'list-rendering',
    'list-rendering',
    'List rendering',
    'Repeated rows/cards/lists intentionally exercise item-scope template-controller handoff.',
  ),
  LocalObjectComponentBoundary: sourcePatternModule(
    'local-object-component-boundary',
    'component-boundary',
    'Local object component boundary',
    'A close parent/child component boundary may pass a typed domain object directly when that is the clean model.',
  ),
  ComponentBoundary: sourcePatternModule(
    'component-boundary',
    'component-boundary',
    'Component boundary',
    'Component inputs or composition model handoffs are intentional app seams rather than accidental forwarding code.',
  ),
  CaptureAttributeFieldShell: sourcePatternModule(
    'capture-attribute-field-shell',
    'component-boundary',
    'Captured field-shell attributes',
    'Wrapper form components capture and forward native attributes/bindings through ...$attrs without becoming value facades.',
  ),
  TemplateControllerFlow: sourcePatternModule(
    'template-controller-flow',
    'template-controller',
    'Template-controller flow',
    'If, repeat, switch, promise, or let scopes are intentional semantic structure rather than markup decoration.',
  ),
  ClassStyleChannels: sourcePatternModule(
    'class-style-channels',
    'style-binding',
    'Class/style binding channels',
    'Class and style bindings exercise binding channels without making the reference CSS a design-system policy.',
  ),
  I18nPlugin: sourcePatternModule(
    'i18n-plugin',
    'plugin-integration',
    'i18n plugin integration',
    '@aurelia/i18n configuration and translation bindings are part of the recipe shape.',
  ),
  PluginIntegration: sourcePatternModule(
    'plugin-integration',
    'plugin-integration',
    'Plugin integration',
    'A framework or community plugin configuration is an intentional recipe capability rather than incidental source.',
  ),
  ValidationPlugin: sourcePatternModule(
    'validation-plugin',
    'plugin-integration',
    'Validation plugin integration',
    '@aurelia/validation-html configuration, rules, validate bindings, and validation errors are part of the recipe shape.',
  ),
  DynamicComposition: sourcePatternModule(
    'dynamic-component-composition',
    'dynamic-composition',
    'Dynamic component composition',
    'au-compose component/template/model handoff is intentional dynamic composition structure.',
  ),
  StateStorePlugin: sourcePatternModule(
    'aurelia-state-store',
    'state-store',
    '@aurelia/state store',
    '@aurelia/state store configuration, actions, and state binding command semantics are the state model.',
  ),
} as const;
