import { auLink } from '../kernel/au-link.js';
import type {
  AddressHandle,
  IdentityHandle,
  ProductHandle,
} from '../kernel/handles.js';
import type { TemplatePhase } from '../kernel/identity.js';
import type { FieldProvenance } from '../kernel/provenance.js';
import type { ResourceDefinitionKind } from '../resources/resource-kind.js';
import type {
  TemplateCompilerServiceReference,
  TemplateCompilerWorldReference,
  TemplateResourceScopeReference,
} from './compiler-world.js';
import type { TemplateParseContextReference } from './parse-context.js';

export const enum TemplateSourceKind {
  /** Markup string from a resource definition, decorator, static field, or convention. */
  Markup = 'markup',
  /** DOM/template object whose authored markup is not available as plain text. */
  DomNode = 'dom-node',
  /** Source is generated by a compiler/tooling pass. */
  Generated = 'generated',
  /** Source exists, but its carrier or representation is still open. */
  Open = 'open',
}

export const enum TemplateCompilationUnitKind {
  /** Root or custom-element template compilation. */
  CustomElement = 'custom-element',
  /** App root template or synthetic root compilation entry. */
  AppRoot = 'app-root',
  /** Nested synthetic view such as a template-controller child template. */
  SyntheticView = 'synthetic-view',
  /** Surrogate/host attribute compilation. */
  Surrogate = 'surrogate',
  /** Unit exists, but the runtime lane is still open. */
  Unknown = 'unknown',
}

export const enum TemplateCompilationContextKind {
  /** Root runtime CompilationContext for one compilation unit. */
  Root = 'root',
  /** Child runtime CompilationContext created from a parent context. */
  Child = 'child',
  /** Context for a synthetic view or nested template-controller template. */
  SyntheticView = 'synthetic-view',
  /** Context exists, but the lane is still open. */
  Unknown = 'unknown',
}

export type TemplateSourceField =
  | 'sourceKind'
  | 'phase'
  | 'owner'
  | 'markup'
  | 'source';

export type TemplateCompilationUnitField =
  | 'unitKind'
  | 'templateSource'
  | 'compilerWorld'
  | 'parseContext'
  | 'rootContext'
  | 'source';

export type TemplateCompilationContextField =
  | 'contextKind'
  | 'compilationUnit'
  | 'compilerWorld'
  | 'parent'
  | 'root'
  | 'resourceScope'
  | 'services'
  | 'parseContext'
  | 'localElements'
  | 'dependencies'
  | 'source';

/** Resource or configuration owner that supplied an authored template source. */
export class TemplateSourceOwnerReference {
  constructor(
    /** Product handle for the owner when materialized, normally a resource definition or header. */
    readonly productHandle: ProductHandle | null,
    /** Identity for the owner when known. */
    readonly identityHandle: IdentityHandle | null,
    /** Resource kind for resource-owned templates. */
    readonly resourceKind: ResourceDefinitionKind | null,
    /** Local display name for traces. */
    readonly localName: string | null,
    /** Source address for the owner declaration or carrier. */
    readonly addressHandle: AddressHandle | null,
  ) {}
}

/** Reference to an authored template source without expanding markup or owner details. */
export class TemplateSourceReference {
  constructor(
    /** Product handle for the template source. */
    readonly productHandle: ProductHandle,
    /** Identity for the template source. */
    readonly identityHandle: IdentityHandle,
    /** Template source lane. */
    readonly sourceKind: TemplateSourceKind,
    /** Template phase represented by the source. */
    readonly phase: TemplatePhase,
    /** Address for the template unit. */
    readonly templateAddressHandle: AddressHandle,
    /** Authored source span or external address for the source carrier. */
    readonly sourceAddressHandle: AddressHandle | null,
  ) {}
}

/** Authored template source before HTML parsing or compiler DOM transformation. */
export class TemplateSource {
  constructor(
    /** Product handle for the materialized-product envelope that represents this source. */
    readonly productHandle: ProductHandle,
    /** Identity for this authored template source. */
    readonly identityHandle: IdentityHandle,
    /** Template source lane. */
    readonly sourceKind: TemplateSourceKind,
    /** Template phase represented by this source. */
    readonly phase: TemplatePhase,
    /** Resource or configuration owner that supplied the source. */
    readonly owner: TemplateSourceOwnerReference | null,
    /** Markup text when the carrier is closed enough to preserve it directly. */
    readonly markup: string | null,
    /** Address for the template unit. */
    readonly templateAddressHandle: AddressHandle,
    /** Authored source span or external address for the source carrier. */
    readonly sourceAddressHandle: AddressHandle | null,
    /** Field-level provenance for source facts that matter to explanation or ambiguity. */
    readonly fieldProvenance: readonly FieldProvenance<TemplateSourceField>[] = [],
  ) {}

  toReference(): TemplateSourceReference {
    return new TemplateSourceReference(
      this.productHandle,
      this.identityHandle,
      this.sourceKind,
      this.phase,
      this.templateAddressHandle,
      this.sourceAddressHandle,
    );
  }
}

/** Reference to a runtime-shaped compilation context without expanding all services. */
export class TemplateCompilationContextReference {
  constructor(
    /** Product handle for the compilation context. */
    readonly productHandle: ProductHandle,
    /** Identity for the compilation context. */
    readonly identityHandle: IdentityHandle,
    /** Runtime context lane. */
    readonly contextKind: TemplateCompilationContextKind,
    /** Source address for the context owner. */
    readonly sourceAddressHandle: AddressHandle | null,
  ) {}
}

/**
 * Runtime-shaped CompilationContext frame.
 *
 * The runtime keeps this as a private helper, but it is the clearest product boundary for tooling: resource lookup,
 * command lookup, attribute parsing, expression parsing, local template scope, and instruction rows all flow through
 * this frame.
 */
@auLink('template-compiler:CompilationContext')
export class TemplateCompilationContext {
  constructor(
    /** Product handle for the materialized-product envelope that represents this context. */
    readonly productHandle: ProductHandle,
    /** Identity for this compilation context. */
    readonly identityHandle: IdentityHandle,
    /** Runtime context lane. */
    readonly contextKind: TemplateCompilationContextKind,
    /** Compilation unit that owns this context. */
    readonly compilationUnitProductHandle: ProductHandle,
    /** Compiler world used by this context. */
    readonly compilerWorld: TemplateCompilerWorldReference,
    /** Parent context for nested templates. */
    readonly parent: TemplateCompilationContextReference | null,
    /** Root context for dependency and local element accumulation. */
    readonly root: TemplateCompilationContextReference | null,
    /** Resource scope used by resolver lookups. */
    readonly resourceScope: TemplateResourceScopeReference,
    /** Runtime compiler services used by this context. */
    readonly services: readonly TemplateCompilerServiceReference[],
    /** Inquiry pressure shared by parser and lowering passes. */
    readonly parseContext: TemplateParseContextReference,
    /** Local custom-element names introduced while compiling the template. */
    readonly localElementNames: readonly string[] = [],
    /** Local dependency identities registered by the compiler context. */
    readonly dependencyIdentityHandles: readonly IdentityHandle[] = [],
    /** Source address for the context owner. */
    readonly sourceAddressHandle: AddressHandle | null = null,
    /** Field-level provenance for source facts that matter to explanation or ambiguity. */
    readonly fieldProvenance: readonly FieldProvenance<TemplateCompilationContextField>[] = [],
  ) {}

  toReference(): TemplateCompilationContextReference {
    return new TemplateCompilationContextReference(
      this.productHandle,
      this.identityHandle,
      this.contextKind,
      this.sourceAddressHandle,
    );
  }
}

/** Reference to a compiler request without expanding source, context, or world details. */
export class TemplateCompilationUnitReference {
  constructor(
    /** Product handle for the compilation unit. */
    readonly productHandle: ProductHandle,
    /** Identity for the compilation unit. */
    readonly identityHandle: IdentityHandle,
    /** Compiler request lane. */
    readonly unitKind: TemplateCompilationUnitKind,
    /** Source address for the unit owner. */
    readonly sourceAddressHandle: AddressHandle | null,
  ) {}
}

/** Compiler-front-door product: source + world + inquiry pressure + root context. */
export class TemplateCompilationUnit {
  constructor(
    /** Product handle for the materialized-product envelope that represents this unit. */
    readonly productHandle: ProductHandle,
    /** Identity for this compilation unit. */
    readonly identityHandle: IdentityHandle,
    /** Compiler request lane. */
    readonly unitKind: TemplateCompilationUnitKind,
    /** Authored source that will be parsed/compiled. */
    readonly templateSource: TemplateSourceReference,
    /** Compiler world selected by configuration and DI world construction. */
    readonly compilerWorld: TemplateCompilerWorldReference,
    /** Inquiry pressure shared by parser and lowering passes. */
    readonly parseContext: TemplateParseContextReference,
    /** Root runtime-shaped compilation context for this unit. */
    readonly rootContext: TemplateCompilationContextReference,
    /** Source address for the unit owner. */
    readonly sourceAddressHandle: AddressHandle | null,
    /** Field-level provenance for source facts that matter to explanation or ambiguity. */
    readonly fieldProvenance: readonly FieldProvenance<TemplateCompilationUnitField>[] = [],
  ) {}

  toReference(): TemplateCompilationUnitReference {
    return new TemplateCompilationUnitReference(
      this.productHandle,
      this.identityHandle,
      this.unitKind,
      this.sourceAddressHandle,
    );
  }
}
