export {
  REF_KINDS,
  KEY_REF_KINDS,
  RESOURCE_REFERENCE_REF_KINDS,
  TEMPLATE_NODE_REF_KINDS,
  SourceSpan,
  ProgramRef,
  SourceFileRef,
  SourceNodeRef,
  SymbolRef,
  KeyRef,
  ContainerWorldRef,
  RegistrationRef,
  TemplateRef,
  CompiledTemplateRef,
  TemplateNodeRef,
  TemplateLocationRef,
  ResourceReferenceRef,
  type T_Ref,
  type RefKind,
  type KeyRefKind,
  type ResourceReferenceRefKind,
  type TemplateNodeRefKind,
} from './refs.js';
export {
  Identifier,
  BindingBehaviorExpression,
  ValueConverterExpression,
  AssignExpression,
  ConditionalExpression,
  AccessGlobalExpression,
  AccessThisExpression,
  AccessBoundaryExpression,
  AccessScopeExpression,
  AccessMemberExpression,
  AccessKeyedExpression,
  ParenExpression,
  NewExpression,
  CallScopeExpression,
  CallMemberExpression,
  CallFunctionExpression,
  CallGlobalExpression,
  BinaryExpression,
  UnaryExpression,
  PrimitiveLiteralExpression,
  ArrayLiteralExpression,
  ObjectLiteralExpression,
  TemplateExpression,
  TaggedTemplateExpression,
  BindingIdentifier,
  ForOfStatement,
  Interpolation,
  BindingPatternDefault,
  BindingPatternHole,
  ArrayBindingPattern,
  ObjectBindingPattern,
  ObjectBindingPatternProperty,
  DestructuringAssignmentExpression,
  ArrowFunction,
  CustomExpression,
  ExpressionParser,
  ExpressionParseSelectionKind,
  SelectedExpressionEntryFamily,
  NoParseSelection,
  ExpressionParseRequest,
  Scanner,
  Token,
  CharCode,
  TokenType,
  TokenFlags,
  hasTokenFlag,
  tokenFlags,
  tokenTypeName,
  ExpressionParseResultKind,
  ExpressionParseResultFlags,
  ExpressionFrontierKind,
  ExpressionExpectedContinuationClass,
  ExpressionCompanionFrameKind,
  ExpressionGapKind,
  MatchedDelimiterKind,
  IteratorActiveRegionKind,
  IteratorOfSeparatorStateKind,
  IteratorTrailingSplitKind,
  InterpolationHoleBoundaryKind,
  InterpolationSuppressedHolePublicationKind,
  expressionParseResultKindFlags,
  hasExpressionParseResultKindFlag,
  ExpressionParseResultInspector,
  MatchedDelimiterEntry,
  ClosedSubtreeRef,
  ExpressionGapDescriptor,
  IteratorOfSeparatorState,
  IteratorTrailingSplitState,
  ExpressionSuccess,
  EmptyExpressionSuccess,
  IteratorSuccess,
  InterpolationSuccess,
  InterpolationAbsent,
  OpaqueSuccess,
  NoExpressionParse,
  CompleteInputParseError,
  PropertyLikeDegradedPublication,
  PropertyLikeFrontierPublication,
  IteratorDegradedPublication,
  IteratorFrontierPublication,
  InterpolationClosedHole,
  InterpolationHoleBoundaryState,
  InterpolationActiveHoleCompanion,
  InterpolationSuppressedHole,
  InterpolationDegradedPublication,
  InterpolationFrontierPublication,
  type ExpressionParseContext,
} from './expression/index.js';
export type {
  AnyBindingExpression,
  ExpressionAstNode,
  ExpressionType,
  IsBindingBehavior,
  CompanionExpressionParseResult,
  CompletedExpressionParseResult,
  NonOwningExpressionParseResult,
  CompletedInputBindingExpression,
  CompletedInputExpressionNode,
  CompletedInputPropertyLikeExpression,
  EmptyExpressionAst,
  ExpressionParseResult,
  ExpressionParseResultPublisher,
  PropertyLikeParseResult,
  IteratorParseResult,
  InterpolationParseResult,
  CustomParseResult,
  PropertyLikeEntryFamily,
  ExpressionParseSelection,
} from './expression/index.js';
export {
  DEPENDENCY_SITE_KINDS,
  DEPENDENCY_ASSOCIATION_SOURCE_KINDS,
  DEPENDENCY_REQUEST_KINDS,
  DEPENDENCY_PROVENANCE_MODES,
  DEPENDENCY_OPEN_SEAM_KINDS,
  DEPENDENCY_RESOLVED_SUBJECT_KINDS,
  INTERFACE_KEY_DEFAULT_REGISTRATION_KINDS,
  LOOKUP_MODIFIER_KINDS,
  DependencyAssociation,
  DependencyAssociationMaterializer,
  DependencyAssociationProvenance,
  DependencyAssociationSource,
  DependencyContributor,
  DependencyMaterialization,
  DependencyOpenSeam,
  DependencyRequest,
  DependencyResolution,
  DependencyResolvedSubject,
  DependencySite,
  DependencySubjectResolver,
  InterfaceKey,
  InterfaceKeyDefaultRegistration,
  LookupModifier,
  type DependencyAssociationMaterializerState,
  type DependencyOpenSeamKind,
  type DependencyAssociationSourceKind,
  type DependencyProvenanceMode,
  type DependencyRequestKind,
  type DependencyResolvedSubjectKind,
  type DependencySiteKind,
  type InterfaceKeyDefaultRegistrationKind,
  type LookupModifierKind,
} from './di/index.js';

export {
  Container,
  type ContainerLookupRequest,
  type ContainerEntry,
  type ContainerState,
} from './container.js';

export {
  APP_TASK_CALLBACK_KINDS,
  APP_TASK_OPEN_SEAM_KINDS,
  APP_TASK_SLOT_KINDS,
  AppTaskCallbackSurface,
  AppTaskContribution,
  AppTaskKeyRequest,
  AppTaskOpenSeam,
  AppTaskScanner,
  type AppTaskCallbackKind,
  type AppTaskOpenSeamKind,
  type AppTaskSlotKind,
} from './app-task.js';
export { AppRoot, type AppRootConfig } from './app-root.js';
export { AppRootStage } from './app-root.js';
export { Aurelia, type AureliaAppConfig } from './aurelia.js';
export { Registration } from './registration.js';
export {
  ANALYZABILITY_BAND_KINDS,
  CONTAINER_STATE_TOPOLOGY_HOOK_KINDS,
  CURRENT_WORLD_SENSITIVITY_KINDS,
  LOOKUP_REGIME_KINDS,
  MATERIALIZATION_TIMING_KINDS,
  OPEN_RESIDUAL_KINDS,
  REGISTRATION_INTAKE_KINDS,
  REGISTRATION_PAYLOAD_KINDS,
  REGISTRATION_PRODUCTION_KINDS,
  REGISTRATION_STAGE_KINDS,
  REGISTRATION_STRATEGY_KINDS,
  REGISTRATION_TRANSITION_CLASS_KINDS,
  RESOURCE_LOOKUP_REGIME_KINDS,
  ContainerStateCandidate,
  ContainerStateClosureBasis,
  ConfigurationRegistrationProduction,
  ConfigurationRegistrationScanner,
  CONTAINER_STATE_OPEN_SEAM_KINDS,
  CONTAINER_STATE_LOOKUP_OPEN_SEAM_KINDS,
  CONTAINER_STATE_LOOKUP_STATUS_KINDS,
  CONTAINER_STATE_PROVENANCE_MODES,
  CONTAINER_STATE_SLOT_KINDS,
  ContainerStateMaterializer,
  ContainerStateOpenSeam,
  ContainerStateEntry,
  ContainerStateLookupEvaluator,
  ContainerStateLookupOpenSeam,
  ContainerStateLookupResult,
  ContainerStateLookupScope,
  ContainerStateProvenance,
  ContainerStateQualification,
  ContainerStateSlot,
  DirectRegisterReferenceMaterializer,
  LookupRequest,
  RegistrationResolverBasis,
  RegistrationIntake,
  RegistrationPayload,
  RegistrationProduction,
  RegistrationTransition,
  ResourceLookupRegime,
  type AnalyzabilityBandKind,
  type ConfigurationRegistrationScannerOptions,
  type ConfigurationRegistrationScannerState,
  type ContainerStateTopologyHookKind,
  type ContainerStateMaterialization,
  type ContainerStateMaterializerOptions,
  type ContainerStateMaterializerState,
  type ContainerStateLookupOpenSeamKind,
  type ContainerStateLookupStatusKind,
  type ContainerStateOpenSeamKind,
  type ContainerStateProvenanceMode,
  type ContainerStateSlotKind,
  type CurrentWorldSensitivityKind,
  type DirectRegisterReferenceInput,
  type DirectRegisterReferenceMaterializationOptions,
  type LookupRequestRegimeKind,
  type LookupRegimeKind,
  type MaterializationTimingKind,
  type OpenResidualKind,
  type RegistrationIntakeKind,
  type RegistrationPayloadKind,
  type RegistrationProductionKind,
  type RegistrationStageKind,
  type RegistrationStrategyKind,
  type RegistrationTransitionClassKind,
  type ResourceLookupRegimeKind,
} from './registrations/index.js';
export { ResourceResolver } from './resource-resolver.js';
export { Resolver } from './resolver.js';
export { TemplateCompiler } from './template-compiler.js';
export {
  DeclarationWorld,
  type DeclarationExport,
  type DeclarationWorldState,
} from './declaration-world.js';
export {
  BundleArray,
  BundleExpansion,
  BundleExpansionScanner,
  BundleMember,
  BundleSpread,
  ConfigurationContribution,
  ConfigurationContributions,
  ConfigurationContributionScanner,
  Configurations,
  ConfigurationScanner,
  HelperCall,
  REGISTRY_FACTORY_METHOD_ROLE_KINDS,
  REGISTRY_OBJECT_ORIGIN_KINDS,
  RegistryFactoryMethod,
  RegistryMethod,
  RegistryObject,
  RegisterArgument,
  type BundleExpansionScannerOptions,
  type BundleExpansionScannerState,
  type ConfigurationContributionScannerOptions,
  type ConfigurationContributionScannerState,
  type ConfigurationContributionsState,
  type ConfigurationScannerOptions,
  type ConfigurationScannerState,
  type ConfigurationSubject,
  type ConfigurationsState,
  type RegistryFactoryMethodRoleKind,
  type RegistryObjectOriginKind,
} from './configurations/index.js';
export {
  ADMISSION_POLICY_KINDS,
  ADMITTED_SUBJECT_CARRIER_KINDS,
  AdmittedSubject,
  SubjectAdmissionScanner,
  type AdmittedSubjectCarrierKind,
  type AdmissionPolicyKind,
  type SubjectAdmissionScannerOptions,
  type SubjectAdmissionScannerState,
} from './admissions/index.js';
export {
  AUTHORED_TEMPLATE_NODE_KINDS,
  AUTHORED_TEMPLATE_OPEN_SEAM_KINDS,
  COMPILER_ATTRIBUTE_BINDABLE_INFO_ORIGIN_KINDS,
  COMPILER_ATTRIBUTE_CLASSIFICATION_LANE_KINDS,
  COMPILER_ATTRIBUTE_CLASSIFICATION_OPEN_SEAM_KINDS,
  COMPILER_ATTRIBUTE_BINDABLE_ASSIGNMENT_SOURCE_KINDS,
  COMPILER_ATTRIBUTE_BINDABLES_INFO_OPEN_SEAM_KINDS,
  COMPILER_ATTRIBUTE_BINDABLE_VALUE_KINDS,
  COMPILER_ATTRIBUTE_HANDLER_STATUS_KINDS,
  COMPILER_ATTRIBUTE_BINDING_LOWERING_OPEN_SEAM_KINDS,
  COMPILER_ATTRIBUTE_PARSE_CANDIDATE_STATUS_KINDS,
  COMPILER_ATTRIBUTE_PARSE_RESULT_STATUS_KINDS,
  COMPILER_ATTRIBUTE_PRIMARY_BINDABLE_MODE_KINDS,
  COMPILER_ATTRIBUTE_SYNTAX_PROVENANCE_KINDS,
  COMPILED_TEMPLATE_OPEN_SEAM_KINDS,
  COMPILER_ANONYMOUS_ELEMENT_TEMPLATE_KINDS,
  COMPILER_CAPABILITY_KINDS,
  COMPILER_VALUE_PARSE_STATUS_KINDS,
  COMPILER_WORLD_OPEN_SEAM_KINDS,
  AuthoredElementNode,
  AuthoredTemplate,
  AuthoredTemplateAttribute,
  AuthoredTemplateFragment,
  AuthoredTemplateNodeProvenance,
  AuthoredTemplateOpenSeam,
  AuthoredTemplateParser,
  AuthoredTextNode,
  AttributePatternCapability,
  BindingCommandCapability,
  CompilerAttributeBindableInfoEntry,
  CompilerAttributeBindablesInfo,
  CompilerAttributeBindablesInfoOpenSeam,
  CompilerAttributePrimaryBindableProvenance,
  CompilerAttributeClassification,
  CompilerAttributeBindableAssignment,
  CompilerAttributeBindableAssignmentProvenance,
  CompilerAttributeBindingLowering,
  CompilerAttributeBindingLoweringOpenSeam,
  CompilerAttributeClassificationProvenance,
  CompilerAttributeClassificationOpenSeam,
  CompilerAttributeClassifier,
  CompilerAttributeHandlerMaterializer,
  CompilerAttributeHandlerResult,
  CompilerAttributeParseCandidate,
  CompilerAttributeParseResult,
  CompilerAttributePatternMatch,
  CompilerAttributeSyntax,
  CompilerAttributeSyntaxProvenance,
  CompilerAttributeParser,
  AttributeInvocationContext,
  AttributeInvocationContextOpenSeam,
  HYDRATION_LOOKUP_ROUTE_KINDS,
  HydrationConstructionContract,
  HydrationConstructionContractMaterializer,
  HydrationLookupRequirement,
  HydrationConstructionRequirement,
  type HydrationLookupRouteKind,
  HYDRATION_PUBLICATION_AVAILABILITY_KINDS,
  HYDRATION_PUBLICATION_BOUNDARY_KINDS,
  HYDRATION_PUBLICATION_TOKEN_KINDS,
  HydrationContext,
  HydrationPublication,
  HydrationPublicationContract,
  HydrationPublicationStateMaterializer,
  ElementInvocationContext,
  ElementInvocationContextOpenSeam,
  CompilerChildWorldBuilder,
  CompilerChildWorldFormation,
  CompilerChildWorldFormationOpenSeam,
  ControllerLocalStateMaterializer,
  CONTROLLER_OWNED_TEMPLATE_BRANCH_KINDS,
  CONTROLLER_OWNED_TEMPLATE_BRANCH_OPEN_SEAM_KINDS,
  CONTROLLER_TEMPLATE_REALIZATION_POLICY_KINDS,
  CompilerAuthoredAttribute,
  CompilerBindingCommandResolver,
  CompilerConsultedWorld,
  CompilerCapabilityScanner,
  Controller,
  AuSlotsInfo,
  CompiledElementNode,
  CompiledTemplate,
  CompiledTemplateOpenSeam,
  CompiledTextNode,
  ElementController,
  CompilerAnonymousElementDefinition,
  CompilerElementAttributeClassification,
  CompilerElementStructuralCarrier,
  CompilerHydrateTemplateControllerInstruction,
  LookupScopeAssemblyBuilder,
  CompilerResourceAdmissionProvenance,
  CompilerResourceResolver,
  CompilerServiceLocator,
  CompilerTemplateCompilerHooks,
  CompilerValueParseRequest,
  CompilerValueParseResult,
  CompilerValueParser,
  CompilerWorldOpenSeam,
  CompilationContext,
  CompilerCustomAttributeBindingLowerer,
  AttributeController,
  ControllerOwnedTemplateBranch,
  ControllerOwnedTemplateBranchOpenSeam,
  PREPARED_RESOURCE_HYDRATION_BUNDLE_MODE_KINDS,
  PREPARED_RESOURCE_HYDRATION_BUNDLE_OPEN_SEAM_KINDS,
  PREPARED_RESOURCE_HYDRATION_INSTRUCTION_KINDS,
  PreparedHydrateAttributeInstruction,
  PreparedHydrateElementInstruction,
  PreparedHydrateTemplateControllerInstruction,
  PreparedResourceHydrationBundle,
  PreparedResourceHydrationBundleOpenSeam,
  RenderLocation,
  SyntheticView,
  TemplateCompilerHookCapability,
  TemplateCompilationEngine,
  TemplateControllerPreparation,
  TemplateControllerPreparationOpenSeam,
  TemplateControllerProfileResolver,
  BuiltinTemplateControllerProfile,
  CustomTemplateControllerProfile,
  TemplateControllerRenderer,
  TemplateControllerStructuralLowerer,
  TemplateControllerStructuralLowering,
  ViewFactory,
  type CompilerAttributeClassificationLaneKind,
  type AttributeInvocationContextOpenSeamKind,
  type HydrationPublicationAvailabilityKind,
  type HydrationPublicationBoundaryKind,
  type HydrationPublicationTokenKind,
  type ElementInvocationContextOpenSeamKind,
  type CompilerAttributeBindableInfoOriginKind,
  type CompilerAttributeBindableAssignmentSourceKind,
  type CompilerAttributeBindablesInfoOpenSeamKind,
  type CompilerAttributeBindableValueKind,
  type CompilerAttributeBindingLoweringOpenSeamKind,
  type CompilerAttributeClassificationOpenSeamKind,
  type CompilerAttributeHandlerStatusKind,
  type CompilerAttributeParseCandidateStatusKind,
  type CompilerAttributeParseResultStatusKind,
  type CompilerAttributeSyntaxProvenanceKind,
  type CompilerCapability,
  type CompilerCapabilityKind,
  type CompilerChildWorldFormationOpenSeamKind,
  type CompilerChildWorldRequestModeKind,
  type ControllerOwnedTemplateBranchKind,
  type ControllerOwnedTemplateBranchOpenSeamKind,
  type ControllerTemplateRealizationPolicyKind,
  type CompilerConsultedWorldState,
  type CompilerCapabilityScannerOptions,
  type CompilerCapabilityScannerState,
  type ControllerKind,
  type BuiltinTemplateControllerFamilyKind,
  type CompiledTemplateNode,
  type CompiledTemplateOpenSeamKind,
  type CompilerAnonymousElementTemplateKind,
  type CompilerAttributePrimaryBindableModeKind,
  type PreparedResourceHydrationBundleModeKind,
  type PreparedResourceHydrationBundleOpenSeamKind,
  type PreparedResourceHydrationInstructionKind,
  type TemplateControllerPreparationOpenSeamKind,
  type TemplateControllerProfileKind,
  type TemplateControllerScopeEffectKind,
  type TemplateControllerTriggerSurfaceKind,
  type TemplateControllerLinkageKind,
  type TemplateControllerViewRealizationPolicyKind,
  type CompilerValueParseStatusKind,
  type CompilerWorldOpenSeamKind,
  type AuthoredTemplateNode,
  type AuthoredTemplateNodeKind,
  type AuthoredTemplateOpenSeamKind,
  type TemplateControllerStructuralParticipant,
} from './compiler/index.js';
export type { TemplateControllerProfile } from './compiler/index.js';
export {
  FRAMEWORK_API_FAMILY_KINDS,
  FRAMEWORK_API_INGRESS_STATUS_KINDS,
  FRAMEWORK_API_ROUTE_STEP_KINDS,
  FrameworkApi,
  FrameworkApiCatalog,
  FrameworkApiIngress,
  FrameworkApiIngressScanner,
  FrameworkApiMatcher,
  FrameworkApiRouteStep,
  type FrameworkApiCatalogState,
  type FrameworkApiFamilyKind,
  type FrameworkApiIngressScannerOptions,
  type FrameworkApiIngressScannerState,
  type FrameworkApiIngressStatusKind,
  type FrameworkApiRouteStepKind,
} from './framework-api/index.js';
export {
  EXPORT_CLASSIFICATION_KINDS,
  Export,
  ExportClassification,
  ExportScanner,
  Exports,
  ExportSurface,
  EXPORT_VALUE_CHECK_KINDS,
  EXPORT_VALUE_SURFACE_KINDS,
  ExportValueSurface,
  type ExportClassificationKind,
  type ExportValueCheckKind,
  type ExportValueSurfaceKind,
  type ExportScannerOptions,
  type ExportScannerState,
  type ExportsState,
} from './exports/index.js';
export {
  BUILTIN_INSTRUCTION_RENDERER_KINDS,
  AU_SLOT_CONTENT_SELECTION_KINDS,
  AU_SLOT_PREPARATION_OPEN_SEAM_KINDS,
  CURRENT_TARGET_PREPARATION_MODE_KINDS,
  CURRENT_TARGET_PREPARATION_OPEN_SEAM_KINDS,
  CUSTOM_ATTRIBUTE_PREPARATION_OPEN_SEAM_KINDS,
  CUSTOM_ELEMENT_PREPARATION_OPEN_SEAM_KINDS,
  RENDERING_OPEN_SEAM_KINDS,
  AuSlotContentSelection,
  AuSlotPreparation,
  AuSlotPreparationOpenSeam,
  CurrentTargetPreparation,
  CurrentTargetPreparationOpenSeam,
  CustomAttributePreparation,
  CustomAttributePreparationOpenSeam,
  CustomAttributeRenderer,
  CustomElementPreparation,
  CustomElementPreparationOpenSeam,
  CustomElementRenderer,
  CustomInstructionRenderer,
  InstructionRendererAdmissionProvenance,
  PassiveInstructionRenderer,
  Rendering,
  RenderingOpenSeam,
  createInstructionRenderer,
  type AuSlotContentSelectionKind,
  type AuSlotPreparationOpenSeamKind,
  type BuiltinInstructionRendererKind,
  type CurrentTargetPreparationModeKind,
  type CurrentTargetPreparationOpenSeamKind,
  type CustomAttributePreparationOpenSeamKind,
  type CustomElementPreparationOpenSeamKind,
  type RenderingOpenSeamKind,
} from './rendering/index.js';
export type { InstructionRenderer } from './rendering/index.js';
export {
  CUSTOM_ATTRIBUTE_LIFECYCLE_CARRIER_KINDS,
  CUSTOM_ATTRIBUTE_LIFECYCLE_HOOK_KINDS,
  CUSTOM_ATTRIBUTE_DEPENDENCY_LINK_SEED_KINDS,
  CUSTOM_ATTRIBUTE_DEPENDENCY_SOURCE_KINDS,
  CUSTOM_ATTRIBUTE_SUPPORT_CARRIER_KINDS,
  CUSTOM_ATTRIBUTE_SUPPORT_FIELD_KINDS,
  CustomAttributeDependencyContribution,
  CustomAttributeDependencyEntry,
  CustomAttributeFieldProvenance,
  CustomAttributeFieldWitness,
  CustomAttributeIdentity,
  CustomAttributeLifecycleHooks,
  CustomAttributeLifecycleHookProvenance,
  CustomAttributeLifecycleHookWitness,
  CustomAttributeMaterializer,
  CustomAttributePolicy,
  type CustomAttributeLifecycleCarrierKind,
  type CustomAttributeLifecycleHookKind,
  type CustomAttributeDependencyLinkSeedKind,
  type CustomAttributeDependencySourceKind,
  type CustomAttributeMaterializerState,
  type CustomAttributeSupportCarrierKind,
  type CustomAttributeSupportFieldKind,
  CUSTOM_ELEMENT_LIFECYCLE_CARRIER_KINDS,
  CUSTOM_ELEMENT_LIFECYCLE_HOOK_KINDS,
  CUSTOM_ELEMENT_CAPTURE_KINDS,
  CUSTOM_ELEMENT_DEPENDENCY_LINK_SEED_KINDS,
  CUSTOM_ELEMENT_DEPENDENCY_SOURCE_KINDS,
  CUSTOM_ELEMENT_PROCESS_CONTENT_KINDS,
  CUSTOM_ELEMENT_SUPPORT_FIELD_KINDS,
  CUSTOM_ELEMENT_SUPPORT_CARRIER_KINDS,
  CUSTOM_ELEMENT_TEMPLATE_SOURCE_KINDS,
  BINDING_COMMAND_EMISSION_SHAPE_KINDS,
  BINDING_BEHAVIOR_SUPPORT_CARRIER_KINDS,
  BINDING_BEHAVIOR_SUPPORT_FIELD_KINDS,
  BINDING_COMMAND_SUPPORT_CARRIER_KINDS,
  BINDING_COMMAND_SUPPORT_FIELD_KINDS,
  BINDING_COMMAND_VALUE_HANDLING_KINDS,
  RESOURCE_DEFINITION_KINDS,
  RESOURCE_CARRIER_KINDS,
  RESOURCE_RECOGNITION_PATH_KINDS,
  RESOURCE_RECOGNITION_STATUSES,
  DEFINITION_CONTRIBUTION_STATUSES,
  DEFINITION_FIELD_KINDS,
  AttributePatternDefinition,
  BindingBehaviorDefinition,
  BindingBehaviorExecutionSurface,
  BindingBehaviorFieldProvenance,
  BindingBehaviorFieldWitness,
  BindingBehaviorIdentity,
  BindingBehaviorMaterializer,
  BindingCommandDefinition,
  BindingCommandBuildBasis,
  BindingCommandInstructionEmission,
  BindingCommandValueHandling,
  BindingCommandFieldProvenance,
  BindingCommandFieldWitness,
  BindingCommandIdentity,
  BindingCommandMaterializer,
  BINDABLE_CALLBACK_TARGET_KINDS,
  BINDABLE_CARRIER_KINDS,
  BINDABLE_FIELD_KINDS,
  BINDABLE_INTERCEPTOR_KINDS,
  CHILDREN_CALLBACK_TARGET_KINDS,
  CHILDREN_DECLARATION_ORIGIN_KINDS,
  CHILDREN_QUERY_KINDS,
  CHILDREN_TRANSFORM_KINDS,
  SLOTTED_CALLBACK_TARGET_KINDS,
  SLOTTED_DECLARATION_ORIGIN_KINDS,
  SLOTTED_QUERY_KINDS,
  SLOTTED_SLOT_TARGET_KINDS,
  CustomAttributeDefinition,
  BindableCallbackTarget,
  BindableEntry,
  BindableFieldProvenance,
  BindableFieldWitness,
  BindableSurface,
  BindableSurfaceProvenance,
  BindableSurfaceWitness,
  ChildrenCallbackTarget,
  ChildrenDeclaration,
  ChildrenQueryPlan,
  ChildrenSurface,
  ChildrenTransformPlan,
  SlottedCallbackTarget,
  SlottedDeclaration,
  SlottedQueryPlan,
  SlottedSlotTarget,
  SlottedSurface,
  CUSTOM_ELEMENT_SLOT_TARGET_KINDS,
  CustomElementDefinition,
  CustomElementDeclaredSlot,
  CustomElementDependencySource,
  CustomElementDependencyContribution,
  CustomElementDependencyEntry,
  CustomElementFieldProvenance,
  CustomElementFieldWitness,
  CustomElementIdentity,
  CustomElementLifecycleHooks,
  CustomElementLifecycleHookProvenance,
  CustomElementLifecycleHookWitness,
  CustomElementMaterializer,
  CustomElementPolicy,
  CustomElementSlotTopology,
  CustomElementTemplateSource,
  DefinitionCarrier,
  DefinitionCarrierCollector,
  DefinitionFieldContribution,
  ResourceCandidate,
  ResourceCarrier,
  ResourceRecognitionPath,
  ResourceRecognizer,
  Resources,
  TemplateControllerDefinition,
  ValueConverterDefinition,
  WATCH_CALLBACK_TARGET_KINDS,
  WATCH_DECLARATION_ORIGIN_KINDS,
  WATCH_EXPRESSION_KINDS,
  WATCH_FLUSH_KINDS,
  WatchCallbackTarget,
  WatchDeclaration,
  WatchExpressionPlan,
  WatchSurface,
  VALUE_CONVERTER_SUPPORT_CARRIER_KINDS,
  VALUE_CONVERTER_SUPPORT_FIELD_KINDS,
  ValueConverterBehavior,
  ValueConverterFieldProvenance,
  ValueConverterFieldWitness,
  ValueConverterIdentity,
  ValueConverterMaterializer,
  type DefinitionContributionStatus,
  type DefinitionCarrierCollectorOptions,
  type DefinitionCarrierCollectorState,
  type DefinitionFieldKind,
  type ResourceCarrierKind,
  type BindableCallbackTargetKind,
  type BindableCarrierKind,
  type BindableFieldKind,
  type BindableInterceptorKind,
  type ChildrenCallbackTargetKind,
  type ChildrenDeclarationOriginKind,
  type ChildrenQueryKind,
  type ChildrenTransformKind,
  type SlottedCallbackTargetKind,
  type SlottedDeclarationOriginKind,
  type SlottedQueryKind,
  type SlottedSlotTargetKind,
  type CustomElementCaptureKind,
  type CustomElementDependencyLinkSeedKind,
  type CustomElementDependencySourceKind,
  type CustomElementLifecycleCarrierKind,
  type CustomElementLifecycleHookKind,
  type CustomElementMaterializerState,
  type CustomElementProcessContentKind,
  type CustomElementSlotTargetKind,
  type CustomElementSupportCarrierKind,
  type CustomElementSupportFieldKind,
  type CustomElementTemplateSourceKind,
  type BindingCommandEmissionShapeKind,
  type BindingBehaviorMaterializerState,
  type BindingBehaviorSupportCarrierKind,
  type BindingBehaviorSupportFieldKind,
  type BindingCommandSupportCarrierKind,
  type BindingCommandSupportFieldKind,
  type BindingCommandValueHandlingKind,
  type BindingCommandMaterializerState,
  type ResourceDefinition,
  type ResourceDefinitionKind,
  type ResourceDefinitionState,
  type ResourceDefinitionType,
  type WatchCallbackTargetKind,
  type WatchDeclarationOriginKind,
  type WatchExpressionKind,
  type WatchFlushKind,
  type ResourceRecognitionPathKind,
  type ResourceRecognitionStatus,
  type ResourceRecognizerOptions,
  type ResourceRecognizerState,
  type ResourcesState,
  type ValueConverterMaterializerState,
  type ValueConverterSupportCarrierKind,
  type ValueConverterSupportFieldKind,
} from './resources/index.js';
export {
  TYPESCRIPT_WORLD_CONSTRUCTION_OPEN_SEAM_KINDS,
  TypeScriptWorldConstruction,
  TypeScriptWorldConstructionOpenSeam,
  TypeScriptWorldConstructionScanner,
  TypeScriptWorldConstructions,
  type TypeScriptWorldConstructionOpenSeamKind,
  type TypeScriptWorldConstructionScannerOptions,
  type TypeScriptWorldConstructionScannerState,
  type TypeScriptWorldConstructionsState,
} from './world-construction/index.js';
export { Framework, type FrameworkOptions } from './framework.js';
export { Project, type ProjectOptions } from './project.js';
export { Workspace, type WorkspaceOptions } from './workspace.js';
export {
  TOOLING_ACTIVATION_STATUS_KINDS,
  BUILD_TOOL_KINDS,
  AURELIA_CONVENTIONS_DRIVER_KINDS,
  TOOLING_EVIDENCE_CARRIER_KINDS,
  ToolingEvidence,
  BuildToolActivation,
  AureliaConventionsActivation,
  ToolingEnvironment,
  ToolingEnvironmentScanner,
  type ToolingActivationStatusKind,
  type BuildToolKind,
  type AureliaConventionsDriverKind,
  type ToolingEvidenceCarrierKind,
  type ToolingEnvironmentScannerOptions,
  type ToolingEnvironmentScannerState,
} from './tooling/index.js';
