export {
  REF_KINDS,
  KEY_REF_KINDS,
  RESOURCE_REFERENCE_REF_KINDS,
  TEMPLATE_NODE_REF_KINDS,
  SourceSpan,
  ProgramRef,
  SourceFileRef,
  SourceNodeRef,
  SymbolRef,
  KeyRef,
  ContainerWorldRef,
  RegistrationRef,
  TemplateRef,
  CompiledTemplateRef,
  TemplateNodeRef,
  TemplateLocationRef,
  ResourceReferenceRef,
  type T_Ref,
  type RefKind,
  type KeyRefKind,
  type ResourceReferenceRefKind,
  type TemplateNodeRefKind,
} from './refs.js';
export {
  DEPENDENCY_SITE_KINDS,
  DEPENDENCY_ASSOCIATION_SOURCE_KINDS,
  DEPENDENCY_REQUEST_KINDS,
  DEPENDENCY_PROVENANCE_MODES,
  DEPENDENCY_OPEN_SEAM_KINDS,
  DEPENDENCY_RESOLVED_SUBJECT_KINDS,
  INTERFACE_KEY_DEFAULT_REGISTRATION_KINDS,
  LOOKUP_MODIFIER_KINDS,
  DependencyAssociation,
  DependencyAssociationMaterializer,
  DependencyAssociationProvenance,
  DependencyAssociationSource,
  DependencyContributor,
  DependencyMaterialization,
  DependencyOpenSeam,
  DependencyRequest,
  DependencyResolution,
  DependencyResolvedSubject,
  DependencySite,
  DependencySubjectResolver,
  InterfaceKey,
  InterfaceKeyDefaultRegistration,
  LookupModifier,
  type DependencyAssociationMaterializerState,
  type DependencyOpenSeamKind,
  type DependencyAssociationSourceKind,
  type DependencyProvenanceMode,
  type DependencyRequestKind,
  type DependencyResolvedSubjectKind,
  type DependencySiteKind,
  type InterfaceKeyDefaultRegistrationKind,
  type LookupModifierKind,
} from './di/index.js';

export {
  Container,
  type ContainerLookupRequest,
  type ContainerEntry,
  type ContainerState,
} from './container.js';

export { AppRoot, type AppRootConfig } from './app-root.js';
export { Aurelia, type AureliaAppConfig } from './aurelia.js';
export { Registration } from './registration.js';
export {
  ANALYZABILITY_BAND_KINDS,
  CONTAINER_STATE_TOPOLOGY_HOOK_KINDS,
  CURRENT_WORLD_SENSITIVITY_KINDS,
  LOOKUP_REGIME_KINDS,
  MATERIALIZATION_TIMING_KINDS,
  OPEN_RESIDUAL_KINDS,
  REGISTRATION_INTAKE_KINDS,
  REGISTRATION_PAYLOAD_KINDS,
  REGISTRATION_PRODUCTION_KINDS,
  REGISTRATION_STAGE_KINDS,
  REGISTRATION_STRATEGY_KINDS,
  REGISTRATION_TRANSITION_CLASS_KINDS,
  RESOURCE_LOOKUP_REGIME_KINDS,
  ContainerStateCandidate,
  ContainerStateClosureBasis,
  ConfigurationRegistrationProduction,
  ConfigurationRegistrationScanner,
  CONTAINER_STATE_OPEN_SEAM_KINDS,
  CONTAINER_STATE_PROVENANCE_MODES,
  CONTAINER_STATE_SLOT_KINDS,
  ContainerStateMaterializer,
  ContainerStateOpenSeam,
  ContainerStateEntry,
  ContainerStateProvenance,
  ContainerStateQualification,
  ContainerStateSlot,
  LookupRequest,
  RegistrationResolverBasis,
  RegistrationIntake,
  RegistrationPayload,
  RegistrationProduction,
  RegistrationTransition,
  ResourceLookupRegime,
  type AnalyzabilityBandKind,
  type ConfigurationRegistrationScannerOptions,
  type ConfigurationRegistrationScannerState,
  type ContainerStateTopologyHookKind,
  type ContainerStateMaterialization,
  type ContainerStateMaterializerOptions,
  type ContainerStateMaterializerState,
  type ContainerStateOpenSeamKind,
  type ContainerStateProvenanceMode,
  type ContainerStateSlotKind,
  type CurrentWorldSensitivityKind,
  type LookupRequestRegimeKind,
  type LookupRegimeKind,
  type MaterializationTimingKind,
  type OpenResidualKind,
  type RegistrationIntakeKind,
  type RegistrationPayloadKind,
  type RegistrationProductionKind,
  type RegistrationStageKind,
  type RegistrationStrategyKind,
  type RegistrationTransitionClassKind,
  type ResourceLookupRegimeKind,
} from './registrations/index.js';
export { ResourceResolver } from './resource-resolver.js';
export { Resolver } from './resolver.js';
export { TemplateCompiler } from './template-compiler.js';
export {
  DeclarationWorld,
  type DeclarationExport,
  type DeclarationWorldState,
} from './declaration-world.js';
export {
  BundleArray,
  BundleExpansion,
  BundleExpansionScanner,
  BundleMember,
  BundleSpread,
  ConfigurationContribution,
  ConfigurationContributions,
  ConfigurationContributionScanner,
  Configurations,
  ConfigurationScanner,
  HelperCall,
  REGISTRY_FACTORY_METHOD_ROLE_KINDS,
  REGISTRY_OBJECT_ORIGIN_KINDS,
  RegistryFactoryMethod,
  RegistryMethod,
  RegistryObject,
  RegisterArgument,
  type BundleExpansionScannerOptions,
  type BundleExpansionScannerState,
  type ConfigurationContributionScannerOptions,
  type ConfigurationContributionScannerState,
  type ConfigurationContributionsState,
  type ConfigurationScannerOptions,
  type ConfigurationScannerState,
  type ConfigurationSubject,
  type ConfigurationsState,
  type RegistryFactoryMethodRoleKind,
  type RegistryObjectOriginKind,
} from './configurations/index.js';
export {
  ADMISSION_POLICY_KINDS,
  ADMITTED_SUBJECT_CARRIER_KINDS,
  AdmittedSubject,
  SubjectAdmissionScanner,
  type AdmittedSubjectCarrierKind,
  type AdmissionPolicyKind,
  type SubjectAdmissionScannerOptions,
  type SubjectAdmissionScannerState,
} from './admissions/index.js';
export {
  COMPILER_CAPABILITY_KINDS,
  AttributePatternCapability,
  BindingCommandCapability,
  CompilerCapabilityScanner,
  TemplateCompilerHookCapability,
  type CompilerCapability,
  type CompilerCapabilityKind,
  type CompilerCapabilityScannerOptions,
  type CompilerCapabilityScannerState,
} from './compiler/index.js';
export {
  FRAMEWORK_API_FAMILY_KINDS,
  FRAMEWORK_API_INGRESS_STATUS_KINDS,
  FRAMEWORK_API_ROUTE_STEP_KINDS,
  FrameworkApi,
  FrameworkApiCatalog,
  FrameworkApiIngress,
  FrameworkApiIngressScanner,
  FrameworkApiMatcher,
  FrameworkApiRouteStep,
  type FrameworkApiCatalogState,
  type FrameworkApiFamilyKind,
  type FrameworkApiIngressScannerOptions,
  type FrameworkApiIngressScannerState,
  type FrameworkApiIngressStatusKind,
  type FrameworkApiRouteStepKind,
} from './framework-api/index.js';
export {
  EXPORT_CLASSIFICATION_KINDS,
  Export,
  ExportClassification,
  ExportScanner,
  Exports,
  ExportSurface,
  EXPORT_VALUE_CHECK_KINDS,
  EXPORT_VALUE_SURFACE_KINDS,
  ExportValueSurface,
  type ExportClassificationKind,
  type ExportValueCheckKind,
  type ExportValueSurfaceKind,
  type ExportScannerOptions,
  type ExportScannerState,
  type ExportsState,
} from './exports/index.js';
export {
  CUSTOM_ELEMENT_BINDABLE_FIELD_KINDS,
  CUSTOM_ELEMENT_BINDABLE_INTERCEPTOR_KINDS,
  CUSTOM_ELEMENT_CAPTURE_KINDS,
  CUSTOM_ELEMENT_DEPENDENCY_LINK_SEED_KINDS,
  CUSTOM_ELEMENT_DEPENDENCY_SOURCE_KINDS,
  CUSTOM_ELEMENT_PROCESS_CONTENT_KINDS,
  CUSTOM_ELEMENT_SUPPORT_FIELD_KINDS,
  CUSTOM_ELEMENT_SUPPORT_CARRIER_KINDS,
  CUSTOM_ELEMENT_TEMPLATE_SOURCE_KINDS,
  RESOURCE_DEFINITION_KINDS,
  RESOURCE_CARRIER_KINDS,
  RESOURCE_RECOGNITION_PATH_KINDS,
  RESOURCE_RECOGNITION_STATUSES,
  DEFINITION_CONTRIBUTION_STATUSES,
  DEFINITION_FIELD_KINDS,
  AttributePatternDefinition,
  BindingBehaviorDefinition,
  BindingCommandDefinition,
  CustomAttributeDefinition,
  CustomElementBindableEntry,
  CustomElementBindableFieldProvenance,
  CustomElementBindableFieldWitness,
  CustomElementBindableSurface,
  CustomElementDefinition,
  CustomElementDependencySource,
  CustomElementDependencyContribution,
  CustomElementDependencyEntry,
  CustomElementFieldProvenance,
  CustomElementFieldWitness,
  CustomElementIdentity,
  CustomElementMaterializer,
  CustomElementPolicy,
  CustomElementTemplateSource,
  DefinitionCarrier,
  DefinitionCarrierCollector,
  DefinitionFieldContribution,
  ResourceCandidate,
  ResourceCarrier,
  ResourceRecognitionPath,
  ResourceRecognizer,
  Resources,
  TemplateControllerDefinition,
  ValueConverterDefinition,
  type DefinitionContributionStatus,
  type DefinitionCarrierCollectorOptions,
  type DefinitionCarrierCollectorState,
  type DefinitionFieldKind,
  type ResourceCarrierKind,
  type CustomElementBindableFieldKind,
  type CustomElementBindableInterceptorKind,
  type CustomElementCaptureKind,
  type CustomElementDependencyLinkSeedKind,
  type CustomElementDependencySourceKind,
  type CustomElementMaterializerState,
  type CustomElementProcessContentKind,
  type CustomElementSupportCarrierKind,
  type CustomElementSupportFieldKind,
  type CustomElementTemplateSourceKind,
  type ResourceDefinition,
  type ResourceDefinitionKind,
  type ResourceDefinitionState,
  type ResourceDefinitionType,
  type ResourceRecognitionPathKind,
  type ResourceRecognitionStatus,
  type ResourceRecognizerOptions,
  type ResourceRecognizerState,
  type ResourcesState,
} from './resources/index.js';
export { Framework, type FrameworkOptions } from './framework.js';
export { Project, type ProjectOptions } from './project.js';
export { Workspace, type WorkspaceOptions } from './workspace.js';
