// @generated by packages/semantic-runtime/scripts/generate-svg-analyzer-data.mjs
// Source of truth: aurelia/packages/runtime-html/src/observation/svg-analyzer.ts
// Do not edit by hand.

const svgElementAttributes = {
  "a": ["class", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "target", "transform", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "altglyph": ["class", "dx", "dy", "externalresourcesrequired", "format", "glyphref", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "rotate", "style", "systemlanguage", "x", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space", "y"],
  "altglyphdef": ["id", "xml:base", "xml:lang", "xml:space"],
  "altglyphitem": ["id", "xml:base", "xml:lang", "xml:space"],
  "animate": ["accumulate", "additive", "attributename", "attributetype", "begin", "by", "calcmode", "dur", "end", "externalresourcesrequired", "fill", "from", "id", "keysplines", "keytimes", "max", "min", "onbegin", "onend", "onload", "onrepeat", "repeatcount", "repeatdur", "requiredextensions", "requiredfeatures", "restart", "systemlanguage", "to", "values", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "animatecolor": ["accumulate", "additive", "attributename", "attributetype", "begin", "by", "calcmode", "dur", "end", "externalresourcesrequired", "fill", "from", "id", "keysplines", "keytimes", "max", "min", "onbegin", "onend", "onload", "onrepeat", "repeatcount", "repeatdur", "requiredextensions", "requiredfeatures", "restart", "systemlanguage", "to", "values", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "animatemotion": ["accumulate", "additive", "begin", "by", "calcmode", "dur", "end", "externalresourcesrequired", "fill", "from", "id", "keypoints", "keysplines", "keytimes", "max", "min", "onbegin", "onend", "onload", "onrepeat", "origin", "path", "repeatcount", "repeatdur", "requiredextensions", "requiredfeatures", "restart", "rotate", "systemlanguage", "to", "values", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "animatetransform": ["accumulate", "additive", "attributename", "attributetype", "begin", "by", "calcmode", "dur", "end", "externalresourcesrequired", "fill", "from", "id", "keysplines", "keytimes", "max", "min", "onbegin", "onend", "onload", "onrepeat", "repeatcount", "repeatdur", "requiredextensions", "requiredfeatures", "restart", "systemlanguage", "to", "type", "values", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "circle": ["class", "cx", "cy", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "r", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "xml:base", "xml:lang", "xml:space"],
  "clippath": ["class", "clippathunits", "externalresourcesrequired", "id", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "xml:base", "xml:lang", "xml:space"],
  "color-profile": ["id", "local", "name", "rendering-intent", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "cursor": ["externalresourcesrequired", "id", "requiredextensions", "requiredfeatures", "systemlanguage", "x", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space", "y"],
  "defs": ["class", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "xml:base", "xml:lang", "xml:space"],
  "desc": ["class", "id", "style", "xml:base", "xml:lang", "xml:space"],
  "ellipse": ["class", "cx", "cy", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "rx", "ry", "style", "systemlanguage", "transform", "xml:base", "xml:lang", "xml:space"],
  "feblend": ["class", "height", "id", "in", "in2", "mode", "result", "style", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "fecolormatrix": ["class", "height", "id", "in", "result", "style", "type", "values", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "fecomponenttransfer": ["class", "height", "id", "in", "result", "style", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "fecomposite": ["class", "height", "id", "in", "in2", "k1", "k2", "k3", "k4", "operator", "result", "style", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "feconvolvematrix": ["bias", "class", "divisor", "edgemode", "height", "id", "in", "kernelmatrix", "kernelunitlength", "order", "preservealpha", "result", "style", "targetx", "targety", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "fediffuselighting": ["class", "diffuseconstant", "height", "id", "in", "kernelunitlength", "result", "style", "surfacescale", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "fedisplacementmap": ["class", "height", "id", "in", "in2", "result", "scale", "style", "width", "x", "xchannelselector", "xml:base", "xml:lang", "xml:space", "y", "ychannelselector"],
  "fedistantlight": ["azimuth", "elevation", "id", "xml:base", "xml:lang", "xml:space"],
  "feflood": ["class", "height", "id", "result", "style", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "fefunca": ["amplitude", "exponent", "id", "intercept", "offset", "slope", "tablevalues", "type", "xml:base", "xml:lang", "xml:space"],
  "fefuncb": ["amplitude", "exponent", "id", "intercept", "offset", "slope", "tablevalues", "type", "xml:base", "xml:lang", "xml:space"],
  "fefuncg": ["amplitude", "exponent", "id", "intercept", "offset", "slope", "tablevalues", "type", "xml:base", "xml:lang", "xml:space"],
  "fefuncr": ["amplitude", "exponent", "id", "intercept", "offset", "slope", "tablevalues", "type", "xml:base", "xml:lang", "xml:space"],
  "fegaussianblur": ["class", "height", "id", "in", "result", "stddeviation", "style", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "feimage": ["class", "externalresourcesrequired", "height", "id", "preserveaspectratio", "result", "style", "width", "x", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space", "y"],
  "femerge": ["class", "height", "id", "result", "style", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "femergenode": ["id", "xml:base", "xml:lang", "xml:space"],
  "femorphology": ["class", "height", "id", "in", "operator", "radius", "result", "style", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "feoffset": ["class", "dx", "dy", "height", "id", "in", "result", "style", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "fepointlight": ["id", "x", "xml:base", "xml:lang", "xml:space", "y", "z"],
  "fespecularlighting": ["class", "height", "id", "in", "kernelunitlength", "result", "specularconstant", "specularexponent", "style", "surfacescale", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "fespotlight": ["id", "limitingconeangle", "pointsatx", "pointsaty", "pointsatz", "specularexponent", "x", "xml:base", "xml:lang", "xml:space", "y", "z"],
  "fetile": ["class", "height", "id", "in", "result", "style", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "feturbulence": ["basefrequency", "class", "height", "id", "numoctaves", "result", "seed", "stitchtiles", "style", "type", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "filter": ["class", "externalresourcesrequired", "filterres", "filterunits", "height", "id", "primitiveunits", "style", "width", "x", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space", "y"],
  "font": ["class", "externalresourcesrequired", "horiz-adv-x", "horiz-origin-x", "horiz-origin-y", "id", "style", "vert-adv-y", "vert-origin-x", "vert-origin-y", "xml:base", "xml:lang", "xml:space"],
  "font-face": ["accent-height", "alphabetic", "ascent", "bbox", "cap-height", "descent", "font-family", "font-size", "font-stretch", "font-style", "font-variant", "font-weight", "hanging", "id", "ideographic", "mathematical", "overline-position", "overline-thickness", "panose-1", "slope", "stemh", "stemv", "strikethrough-position", "strikethrough-thickness", "underline-position", "underline-thickness", "unicode-range", "units-per-em", "v-alphabetic", "v-hanging", "v-ideographic", "v-mathematical", "widths", "x-height", "xml:base", "xml:lang", "xml:space"],
  "font-face-format": ["id", "string", "xml:base", "xml:lang", "xml:space"],
  "font-face-name": ["id", "name", "xml:base", "xml:lang", "xml:space"],
  "font-face-src": ["id", "xml:base", "xml:lang", "xml:space"],
  "font-face-uri": ["id", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "foreignobject": ["class", "externalresourcesrequired", "height", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "g": ["class", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "xml:base", "xml:lang", "xml:space"],
  "glyph": ["arabic-form", "class", "d", "glyph-name", "horiz-adv-x", "id", "lang", "orientation", "style", "unicode", "vert-adv-y", "vert-origin-x", "vert-origin-y", "xml:base", "xml:lang", "xml:space"],
  "glyphref": ["class", "dx", "dy", "format", "glyphref", "id", "style", "x", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space", "y"],
  "hkern": ["g1", "g2", "id", "k", "u1", "u2", "xml:base", "xml:lang", "xml:space"],
  "image": ["class", "externalresourcesrequired", "height", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "preserveaspectratio", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "width", "x", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space", "y"],
  "line": ["class", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "x1", "x2", "xml:base", "xml:lang", "xml:space", "y1", "y2"],
  "lineargradient": ["class", "externalresourcesrequired", "gradienttransform", "gradientunits", "id", "spreadmethod", "style", "x1", "x2", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space", "y1", "y2"],
  "marker": ["class", "externalresourcesrequired", "id", "markerheight", "markerunits", "markerwidth", "orient", "preserveaspectratio", "refx", "refy", "style", "viewbox", "xml:base", "xml:lang", "xml:space"],
  "mask": ["class", "externalresourcesrequired", "height", "id", "maskcontentunits", "maskunits", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "metadata": ["id", "xml:base", "xml:lang", "xml:space"],
  "missing-glyph": ["class", "d", "horiz-adv-x", "id", "style", "vert-adv-y", "vert-origin-x", "vert-origin-y", "xml:base", "xml:lang", "xml:space"],
  "mpath": ["externalresourcesrequired", "id", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "path": ["class", "d", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "pathlength", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "xml:base", "xml:lang", "xml:space"],
  "pattern": ["class", "externalresourcesrequired", "height", "id", "patterncontentunits", "patterntransform", "patternunits", "preserveaspectratio", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "viewbox", "width", "x", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space", "y"],
  "polygon": ["class", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "points", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "xml:base", "xml:lang", "xml:space"],
  "polyline": ["class", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "points", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "xml:base", "xml:lang", "xml:space"],
  "radialgradient": ["class", "cx", "cy", "externalresourcesrequired", "fx", "fy", "gradienttransform", "gradientunits", "id", "r", "spreadmethod", "style", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "rect": ["class", "externalresourcesrequired", "height", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "rx", "ry", "style", "systemlanguage", "transform", "width", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "script": ["externalresourcesrequired", "id", "type", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "set": ["attributename", "attributetype", "begin", "dur", "end", "externalresourcesrequired", "fill", "id", "max", "min", "onbegin", "onend", "onload", "onrepeat", "repeatcount", "repeatdur", "requiredextensions", "requiredfeatures", "restart", "systemlanguage", "to", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "stop": ["class", "id", "offset", "style", "xml:base", "xml:lang", "xml:space"],
  "style": ["id", "media", "title", "type", "xml:base", "xml:lang", "xml:space"],
  "svg": ["baseprofile", "class", "contentscripttype", "contentstyletype", "externalresourcesrequired", "height", "id", "onabort", "onactivate", "onclick", "onerror", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "onresize", "onscroll", "onunload", "onzoom", "preserveaspectratio", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "version", "viewbox", "width", "x", "xml:base", "xml:lang", "xml:space", "y", "zoomandpan"],
  "switch": ["class", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "xml:base", "xml:lang", "xml:space"],
  "symbol": ["class", "externalresourcesrequired", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "preserveaspectratio", "style", "viewbox", "xml:base", "xml:lang", "xml:space"],
  "text": ["class", "dx", "dy", "externalresourcesrequired", "id", "lengthadjust", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "rotate", "style", "systemlanguage", "textlength", "transform", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "textpath": ["class", "externalresourcesrequired", "id", "lengthadjust", "method", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "spacing", "startoffset", "style", "systemlanguage", "textlength", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space"],
  "title": ["class", "id", "style", "xml:base", "xml:lang", "xml:space"],
  "tref": ["class", "dx", "dy", "externalresourcesrequired", "id", "lengthadjust", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "rotate", "style", "systemlanguage", "textlength", "x", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space", "y"],
  "tspan": ["class", "dx", "dy", "externalresourcesrequired", "id", "lengthadjust", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "rotate", "style", "systemlanguage", "textlength", "x", "xml:base", "xml:lang", "xml:space", "y"],
  "use": ["class", "externalresourcesrequired", "height", "id", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "requiredextensions", "requiredfeatures", "style", "systemlanguage", "transform", "width", "x", "xlink:actuate", "xlink:arcrole", "xlink:href", "xlink:role", "xlink:show", "xlink:title", "xlink:type", "xml:base", "xml:lang", "xml:space", "y"],
  "view": ["externalresourcesrequired", "id", "preserveaspectratio", "viewbox", "viewtarget", "xml:base", "xml:lang", "xml:space", "zoomandpan"],
  "vkern": ["g1", "g2", "id", "k", "u1", "u2", "xml:base", "xml:lang", "xml:space"]
} as const;

const svgPresentationElements = ["a", "altglyph", "animate", "animatecolor", "circle", "clippath", "defs", "ellipse", "feblend", "fecolormatrix", "fecomponenttransfer", "fecomposite", "feconvolvematrix", "fediffuselighting", "fedisplacementmap", "feflood", "fegaussianblur", "feimage", "femerge", "femorphology", "feoffset", "fespecularlighting", "fetile", "feturbulence", "filter", "font", "foreignobject", "g", "glyph", "glyphref", "image", "line", "lineargradient", "marker", "mask", "missing-glyph", "path", "pattern", "polygon", "polyline", "radialgradient", "rect", "stop", "svg", "switch", "symbol", "text", "textpath", "tref", "tspan", "use"] as const;

const svgPresentationAttributes = ["alignment-baseline", "baseline-shift", "clip", "clip-path", "clip-rule", "color", "color-interpolation", "color-interpolation-filters", "color-profile", "color-rendering", "cursor", "direction", "display", "dominant-baseline", "enable-background", "fill", "fill-opacity", "fill-rule", "filter", "flood-color", "flood-opacity", "font-family", "font-size", "font-size-adjust", "font-stretch", "font-style", "font-variant", "font-weight", "glyph-orientation-horizontal", "glyph-orientation-vertical", "image-rendering", "kerning", "letter-spacing", "lighting-color", "marker-end", "marker-mid", "marker-start", "mask", "opacity", "overflow", "pointer-events", "shape-rendering", "stop-color", "stop-opacity", "stroke", "stroke-dasharray", "stroke-dashoffset", "stroke-linecap", "stroke-linejoin", "stroke-miterlimit", "stroke-opacity", "stroke-width", "text-anchor", "text-decoration", "text-rendering", "unicode-bidi", "visibility", "word-spacing", "writing-mode"] as const;

const svgElementAttributeLookup = new Map<string, ReadonlySet<string>>(
  Object.entries(svgElementAttributes).map(([elementName, attributes]) => [elementName, new Set(attributes)]),
);
const svgPresentationElementLookup = new Set<string>(svgPresentationElements);
const svgPresentationAttributeLookup = new Set<string>(svgPresentationAttributes);

export function isKnownSvgElement(tagName: string): boolean {
  return svgElementAttributeLookup.has(normalizeSvgKey(tagName));
}

export function isStandardSvgAttribute(tagName: string, attributeName: string): boolean {
  const normalizedTagName = normalizeSvgKey(tagName);
  const normalizedAttributeName = normalizeSvgKey(attributeName);
  return (
    svgPresentationElementLookup.has(normalizedTagName) && svgPresentationAttributeLookup.has(normalizedAttributeName)
  ) || (
    svgElementAttributeLookup.get(normalizedTagName)?.has(normalizedAttributeName) === true
  );
}

function normalizeSvgKey(value: string): string {
  return value.toLowerCase();
}
