import type { DerivationHandle, EvidenceHandle, ProvenanceHandle } from './handles.js';

export const enum ProvenanceRecordKind {
  /** Links one derivation record into compact provenance without embedding the full record. */
  DerivationLink = 'derivation-link',
  /** Explains why a fact or product exists using evidence and derivation links. */
  ProvenanceRecord = 'provenance-record',
  /** Attaches provenance to one field of a larger semantic object. */
  FieldProvenance = 'field-provenance',
}

export const enum ProvenanceMode {
  /** Use when the provenance mode is not known; consumers should avoid trusting the fact. */
  Unknown = 'unknown',
  /** The fact is backed directly by observed source or semantic evidence. */
  Direct = 'direct',
  /** The fact was produced by a transformation or flow rule. */
  Derived = 'derived',
  /** The fact merges evidence from multiple inputs, such as re-exports or configuration layers. */
  Merged = 'merged',
  /** The fact was generated by compiler or tooling policy. */
  Generated = 'generated',
  /** The fact comes from recovery over incomplete or invalid input. */
  Recovered = 'recovered',
  /** The fact comes from a convention rather than explicit syntax. */
  Convention = 'convention',
  /** The fact is grounded in meaningful absence. */
  Absence = 'absence',
  /** The fact records an unresolved seam that downstream consumers may need to surface. */
  Open = 'open',
}

export const enum DerivationLinkRole {
  /** This derivation consumed the owning fact or product as an input. */
  Input = 'input',
  /** This derivation produced the owning fact or product as an output. */
  Output = 'output',
  /** This derivation is useful explanation context but not a direct data dependency. */
  Explanation = 'explanation',
}

/** Compact pointer from provenance to a derivation without embedding the full derivation graph. */
export class DerivationLink {
  /** String discriminator for serialized derivation-link records. */
  readonly kind = ProvenanceRecordKind.DerivationLink;

  constructor(
    /** Handle of the referenced derivation record in the active store. */
    readonly derivationHandle: DerivationHandle,
    /** How the derivation relates to the fact or product carrying this provenance. */
    readonly role: DerivationLinkRole = DerivationLinkRole.Explanation,
  ) {}
}

/** Explanation record for a claim, field, product, or open seam. */
export class ProvenanceRecord {
  /** String discriminator for serialized provenance records. */
  readonly kind = ProvenanceRecordKind.ProvenanceRecord;

  constructor(
    /** Store-local handle for this provenance record. */
    readonly handle: ProvenanceHandle,
    /** High-level provenance mode, such as direct, derived, recovered, or convention. */
    readonly mode: ProvenanceMode,
    /** Direct witness handles supporting this provenance. */
    readonly evidenceHandles: readonly EvidenceHandle[] = [],
    /** Derivation links that can expand the explanation when needed. */
    readonly derivations: readonly DerivationLink[] = [],
    /** Optional short note when evidence and derivations need a compact human/AI hint. */
    readonly note: string | null = null,
  ) {}
}

/** Field-level provenance for objects whose properties come from different evidence. */
export class FieldProvenance<TField extends string = string> {
  /** String discriminator for serialized field-provenance records. */
  readonly kind = ProvenanceRecordKind.FieldProvenance;

  constructor(
    /** Field name on the owning semantic object. */
    readonly field: TField,
    /** Provenance handle explaining this specific field value. */
    readonly provenanceHandle: ProvenanceHandle,
  ) {}
}

/** Read provenance for one field without requiring every model to implement the lookup itself. */
export function readFieldProvenance<TField extends string>(
  /** Field provenance entries from the owning semantic object. */
  provenance: readonly FieldProvenance<TField>[],
  /** Field to look up. */
  field: TField,
): ProvenanceHandle | null {
  return provenance.find((entry) => entry.field === field)?.provenanceHandle ?? null;
}

/** Drop absent field-provenance slots while preserving the exact field type. */
export function compactFieldProvenance<TField extends string>(
  /** Optional field provenance entries collected while materializing an object. */
  provenance: readonly (FieldProvenance<TField> | null | undefined)[],
): readonly FieldProvenance<TField>[] {
  return provenance.filter((entry): entry is FieldProvenance<TField> => entry != null);
}
