import type { ClosureContractDefinition } from "./types.js";

export const CLOSURE_CONTRACT_DEFINITIONS = [
  {
    contractId: "declaration-surface",
    familyId: "witness.declaration.declaration-surface",
    kind: "declaration-surface",
    closability: "closable",
    description: "Closes the relevant declaration search space for identity, field, and bindable facts.",
    blockingDependencies: ["realized-world-consultation"],
    degradationCategory: "world-open",
  },
  {
    contractId: "support-bundle",
    familyId: "witness.support.support-bundle",
    kind: "support-bundle",
    closability: "closable",
    description: "Closes the positive support bundle required by a consuming fact.",
    blockingDependencies: ["realized-world-consultation"],
    degradationCategory: "world-open",
  },
  {
    contractId: "grammar-shape-completeness",
    familyId: "witness.completeness.grammar-shape",
    kind: "completeness",
    closability: "closable",
    description: "Closes the grammar-shape search space needed for safe classification and structure checks.",
    blockingDependencies: ["realized-world-consultation"],
    degradationCategory: "classification-weakened",
  },
  {
    contractId: "resource-admission-completeness",
    familyId: "witness.completeness.resource-admission",
    kind: "completeness",
    closability: "closable",
    description: "Closes the consulted resource-admission search space for safe negative admission and resource-backed absence claims.",
    blockingDependencies: ["realized-world-consultation"],
    degradationCategory: "activation-gap",
  },
  {
    contractId: "vocabulary-admission-completeness",
    familyId: "witness.completeness.vocabulary-admission",
    kind: "completeness",
    closability: "closable",
    description: "Closes the consulted vocabulary-admission search space for safe negative vocabulary claims.",
    blockingDependencies: ["realized-world-consultation"],
    degradationCategory: "world-open",
  },
  {
    contractId: "resource-scope-completeness",
    familyId: "witness.completeness.resource-scope",
    kind: "completeness",
    closability: "closable",
    description: "Closes the reachable resource world at a site for safe negative reachability claims.",
    blockingDependencies: ["realized-world-consultation"],
    degradationCategory: "reachability-open",
  },
  {
    contractId: "template-scope-completeness",
    familyId: "witness.completeness.template-scope",
    kind: "completeness",
    closability: "closable",
    description: "Closes the contributing template-scope frame world at a site for safe negative identifier-resolution claims.",
    blockingDependencies: ["realized-world-consultation"],
    degradationCategory: "reachability-open",
  },
  {
    contractId: "type-closure-completeness",
    familyId: "witness.completeness.type-closure",
    kind: "completeness",
    closability: "open-placeholder",
    description: "Named type-closure witness family with no committed closure source.",
    blockingDependencies: ["type-closure-completeness"],
    degradationCategory: "closure-reopened",
  },
  {
    contractId: "controller-semantics-governed-closure",
    familyId: "claim.governed.controller-semantics",
    kind: "governed",
    closability: "closable",
    description: "Product-authored controller-semantics contract for controller-bearing custom attributes.",
    blockingDependencies: ["realized-world-consultation"],
    degradationCategory: "governed-unassigned",
  },
  {
    contractId: "binding-command-semantics-governed-closure",
    familyId: "claim.governed.binding-command-semantics",
    kind: "governed",
    closability: "closable",
    description: "Product-authored binding-command semantic contract.",
    blockingDependencies: ["classification", "realized-world-consultation"],
    degradationCategory: "governed-unassigned",
  },
  {
    contractId: "attribute-pattern-semantics-governed-closure",
    familyId: "claim.governed.attribute-pattern-semantics",
    kind: "governed",
    closability: "closable",
    description: "Product-authored attribute-pattern semantic contract.",
    blockingDependencies: ["classification", "realized-world-consultation"],
    degradationCategory: "governed-unassigned",
  },
  {
    contractId: "binding-behavior-semantics-governed-closure",
    familyId: "correctness.7.binding-behavior-misuse",
    kind: "governed",
    closability: "open-placeholder",
    description: "Named governed-closure pressure on binding-behavior misuse with no standalone governed family row.",
    blockingDependencies: ["resource-admission-completeness", "resource-scope-completeness"],
    degradationCategory: "governed-unassigned",
  },
  {
    contractId: "composition-contract",
    familyId: "correctness.8.composition",
    kind: "completeness",
    closability: "open-placeholder",
    description: "Composition-specific correctness contract remains explicitly unresolved.",
    blockingDependencies: ["composition-contract"],
  },
] as const satisfies readonly ClosureContractDefinition[];
