import type { FieldSchemaDefinition } from "./types.js";

function field(
  resourceKind: FieldSchemaDefinition["resourceKind"],
  fieldPath: string,
  valueType: string,
  owningFamilyId: string,
  notes?: string,
): FieldSchemaDefinition {
  return {
    schemaId: `${resourceKind}:${fieldPath}`,
    resourceKind,
    fieldPath,
    valueType,
    owningFamilyId,
    notes,
  };
}

export const FIELD_SCHEMA_DEFINITIONS = [
  field("custom-element", "name", "string", "claim.resource.custom-element-field"),
  field("custom-element", "className", "string", "claim.resource.custom-element-field"),
  field("custom-element", "template", "string | null", "claim.resource.custom-element-field"),
  field("custom-element", "containerless", "boolean", "claim.resource.custom-element-field"),
  field(
    "custom-element",
    "shadowOptions",
    "{ mode: 'open' | 'closed' } | null",
    "claim.resource.custom-element-field",
  ),
  field(
    "custom-element",
    "capture",
    "boolean",
    "claim.resource.custom-element-field",
    "Encoded as a boolean even when the underlying framework source carries function-valued semantics.",
  ),
  field(
    "custom-element",
    "processContent",
    "boolean",
    "claim.resource.custom-element-field",
    "Encoded as a boolean even when the underlying framework source carries function-valued semantics.",
  ),
  field("custom-element", "injectable", "boolean", "claim.resource.custom-element-field"),
  field("custom-element", "strict", "boolean | null", "claim.resource.custom-element-field"),
  field(
    "custom-element",
    "aliases",
    "string[]",
    "claim.resource.custom-element-field",
    "Array entries are preserved individually for completeness analysis.",
  ),
  field(
    "custom-element",
    "dependencies",
    "string[]",
    "claim.resource.custom-element-field",
    "Array entries are preserved individually for completeness analysis.",
  ),
  field("custom-element", "hasSlots", "boolean", "claim.resource.custom-element-field"),
  field("custom-attribute", "name", "string", "claim.resource.custom-attribute-field"),
  field("custom-attribute", "className", "string", "claim.resource.custom-attribute-field"),
  field("custom-attribute", "isTemplateController", "boolean", "claim.resource.custom-attribute-field"),
  field("custom-attribute", "noMultiBindings", "boolean", "claim.resource.custom-attribute-field"),
  field("custom-attribute", "containerStrategy", "string | null", "claim.resource.custom-attribute-field"),
  field("custom-attribute", "defaultProperty", "string", "claim.resource.custom-attribute-field"),
  field(
    "custom-attribute",
    "aliases",
    "string[]",
    "claim.resource.custom-attribute-field",
    "Array entries are preserved individually for completeness analysis.",
  ),
  field(
    "custom-attribute",
    "dependencies",
    "string[]",
    "claim.resource.custom-attribute-field",
    "Array entries are preserved individually for completeness analysis.",
  ),
  field("value-converter", "name", "string", "claim.resource.value-converter-field"),
  field("value-converter", "className", "string", "claim.resource.value-converter-field"),
  field("binding-behavior", "name", "string", "claim.resource.binding-behavior-field"),
  field("binding-behavior", "className", "string", "claim.resource.binding-behavior-field"),
  field("binding-command", "name", "string", "claim.resource.binding-command-field"),
  field("binding-command", "commandKind", "string", "claim.resource.binding-command-field"),
  field(
    "binding-command",
    "aliases",
    "string[]",
    "claim.resource.binding-command-field",
    "Array entries are preserved individually for completeness analysis.",
  ),
  field("attribute-pattern", "pattern", "string", "claim.resource.attribute-pattern-field"),
  field("attribute-pattern", "symbols", "string", "claim.resource.attribute-pattern-field"),
  field("local-custom-element", "name", "string", "claim.identity.local-custom-element"),
  field("local-custom-element", "className", "string | null", "claim.identity.local-custom-element"),
  field("local-custom-element", "template", "string | null", "claim.identity.local-custom-element"),
  field(
    "local-custom-element",
    "aliases",
    "string[]",
    "claim.identity.local-custom-element",
    "Broader local-custom-element field coverage remains an explicit residual beyond the committed local-template surface.",
  ),
] as const satisfies readonly FieldSchemaDefinition[];
